# Translations template for neutron.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the neutron project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: neutron 2015.1.dev699.g6a985c8\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-12-14 06:05+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: neutron/context.py:110
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: neutron/manager.py:72
#, python-format
msgid "dhcp_agents_per_network must be >= 1. '%s' is invalid."
msgstr ""

#: neutron/manager.py:84
msgid "Neutron core_plugin not configured!"
msgstr ""

#: neutron/manager.py:140
msgid "Plugin not found."
msgstr ""

#: neutron/manager.py:179
#, python-format
msgid "Multiple plugins for service %s were configured"
msgstr ""

#: neutron/policy.py:252
#, python-format
msgid ""
"Unable to identify a target field from:%s.match should be in the form "
"%%(<field_name>)s"
msgstr ""

#: neutron/policy.py:282
#, python-format
msgid "Unable to find resource name in %s"
msgstr ""

#: neutron/policy.py:291
#, python-format
msgid ""
"Unable to verify match:%(match)s as the parent resource: %(res)s was not "
"found"
msgstr ""

#: neutron/quota.py:35
msgid "Resource name(s) that are supported in quota features"
msgstr ""

#: neutron/quota.py:39
msgid ""
"Default number of resource allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/quota.py:43
msgid "Number of networks allowed per tenant.A negative value means unlimited."
msgstr ""

#: neutron/quota.py:47
msgid "Number of subnets allowed per tenant, A negative value means unlimited."
msgstr ""

#: neutron/quota.py:51
msgid "Number of ports allowed per tenant. A negative value means unlimited."
msgstr ""

#: neutron/quota.py:55
msgid "Default driver to use for quota checks"
msgstr ""

#: neutron/quota.py:149 neutron/quota.py:154
msgid "Access to this resource was denied."
msgstr ""

#: neutron/service.py:41
msgid "Seconds between running periodic tasks"
msgstr ""

#: neutron/service.py:44
msgid "Number of separate API worker processes for service"
msgstr ""

#: neutron/service.py:47
msgid "Number of RPC worker processes for service"
msgstr ""

#: neutron/service.py:50
msgid ""
"Range of seconds to randomly delay when starting the periodic task "
"scheduler to reduce stampeding. (Disable by setting to 0)"
msgstr ""

#: neutron/wsgi.py:49
msgid "Number of backlog requests to configure the socket with"
msgstr ""

#: neutron/wsgi.py:53
msgid ""
"Sets the value of TCP_KEEPIDLE in seconds for each server socket. Not "
"supported on OS X."
msgstr ""

#: neutron/wsgi.py:57
msgid "Number of seconds to keep retrying to listen"
msgstr ""

#: neutron/wsgi.py:60
msgid "Max header line to accommodate large tokens"
msgstr ""

#: neutron/wsgi.py:63
msgid "Enable SSL on the API server"
msgstr ""

#: neutron/wsgi.py:65
msgid "CA certificate file to use to verify connecting clients"
msgstr ""

#: neutron/wsgi.py:68
msgid "Certificate file to use when starting the server securely"
msgstr ""

#: neutron/wsgi.py:71
msgid "Private key file to use when starting the server securely"
msgstr ""

#: neutron/wsgi.py:136
#, python-format
msgid "Unable to find ssl_cert_file : %s"
msgstr ""

#: neutron/wsgi.py:142
#, python-format
msgid "Unable to find ssl_key_file : %s"
msgstr ""

#: neutron/wsgi.py:147
#, python-format
msgid "Unable to find ssl_ca_file : %s"
msgstr ""

#: neutron/wsgi.py:180
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for %(time)d seconds"
msgstr ""

#: neutron/wsgi.py:461
msgid "Cannot understand JSON"
msgstr ""

#: neutron/wsgi.py:627
msgid "You must implement __call__"
msgstr ""

#: neutron/wsgi.py:720 neutron/api/v2/base.py:194 neutron/api/v2/base.py:335
#: neutron/api/v2/base.py:475 neutron/api/v2/base.py:534
#: neutron/extensions/l3agentscheduler.py:51
#: neutron/extensions/l3agentscheduler.py:94
msgid "The resource could not be found."
msgstr ""

#: neutron/wsgi.py:769
msgid "Unsupported Content-Type"
msgstr ""

#: neutron/wsgi.py:773
msgid "Malformed request body"
msgstr ""

#: neutron/wsgi.py:910
#, python-format
msgid "The requested content type %s is invalid."
msgstr ""

#: neutron/wsgi.py:963
msgid "Could not deserialize data"
msgstr ""

#: neutron/agent/dhcp_agent.py:53
msgid "Interval to resync."
msgstr ""

#: neutron/agent/dhcp_agent.py:56
msgid "The driver used to manage the DHCP server."
msgstr ""

#: neutron/agent/dhcp_agent.py:58
msgid "Support Metadata requests on isolated networks."
msgstr ""

#: neutron/agent/dhcp_agent.py:60
msgid ""
"Allows for serving metadata requests from a dedicated network. Requires "
"enable_isolated_metadata = True"
msgstr ""

#: neutron/agent/dhcp_agent.py:64
msgid "Number of threads to use during sync process."
msgstr ""

#: neutron/agent/dhcp_agent.py:67 neutron/agent/l3/agent.py:202
#: neutron/agent/metadata/namespace_proxy.py:166
msgid "Location of Metadata Proxy UNIX domain socket"
msgstr ""

#: neutron/agent/dhcp_agent.py:600
#, python-format
msgid "Agent updated: %(payload)s"
msgstr ""

#: neutron/agent/netns_cleanup_util.py:60
msgid "Delete the namespace by removing all devices."
msgstr ""

#: neutron/agent/ovs_cleanup_util.py:40
msgid ""
"True to delete all ports on all the OpenvSwitch bridges. False to delete "
"ports created by Neutron on integration and external network bridges."
msgstr ""

#: neutron/agent/securitygroups_rpc.py:36
msgid "Driver for security groups firewall in the L2 agent"
msgstr ""

#: neutron/agent/securitygroups_rpc.py:40
msgid ""
"Controls whether the neutron security group API is enabled in the server."
" It should be false when using no security groups or using the nova "
"security group API."
msgstr ""

#: neutron/agent/securitygroups_rpc.py:47
msgid "Use ipset to speed-up the iptables based security groups."
msgstr ""

#: neutron/agent/common/config.py:29
msgid "Root helper application."
msgstr ""

#: neutron/agent/common/config.py:34
msgid ""
"Seconds between nodes reporting state to server; should be less than "
"agent_down_time, best if it is half or less than agent_down_time."
msgstr ""

#: neutron/agent/common/config.py:41
msgid "The driver used to manage the virtual interface."
msgstr ""

#: neutron/agent/common/config.py:46
msgid "Allow overlapping IP."
msgstr ""

#: neutron/agent/common/config.py:51
msgid "Add comments to iptables rules."
msgstr ""

#: neutron/agent/common/config.py:111
msgid ""
"DEFAULT.root_helper is deprecated! Please move root_helper configuration "
"to [AGENT] section."
msgstr ""

#: neutron/agent/common/config.py:122
msgid "Top-level directory for maintaining dhcp state"
msgstr ""

#: neutron/agent/l3/agent.py:163
msgid ""
"The working mode for the agent. Allowed modes are: 'legacy' - this "
"preserves the existing behavior where the L3 agent is deployed on a "
"centralized networking node to provide L3 services like DNAT, and SNAT. "
"Use this mode if you do not want to adopt DVR. 'dvr' - this mode enables "
"DVR functionality and must be used for an L3 agent that runs on a compute"
" host. 'dvr_snat' - this enables centralized SNAT support in conjunction "
"with DVR.  This mode must be used for an L3 agent running on a "
"centralized node (or in single-host deployments, e.g. devstack)"
msgstr ""

#: neutron/agent/l3/agent.py:176 neutron/debug/debug_agent.py:42
msgid "Name of bridge used for external network traffic."
msgstr ""

#: neutron/agent/l3/agent.py:180
msgid "TCP Port used by Neutron metadata namespace proxy."
msgstr ""

#: neutron/agent/l3/agent.py:184
msgid ""
"Send this many gratuitous ARPs for HA setup, if less than or equal to 0, "
"the feature is disabled"
msgstr ""

#: neutron/agent/l3/agent.py:187
msgid ""
"If namespaces is disabled, the l3 agent can only configure a router that "
"has the matching router ID."
msgstr ""

#: neutron/agent/l3/agent.py:192
msgid "Agent should implement routers with no gateway"
msgstr ""

#: neutron/agent/l3/agent.py:194
msgid "UUID of external network for routers implemented by the agents."
msgstr ""

#: neutron/agent/l3/agent.py:197
msgid "Allow running metadata proxy."
msgstr ""

#: neutron/agent/l3/agent.py:199
msgid "Delete namespace after removing a router."
msgstr ""

#: neutron/agent/l3/agent.py:449
msgid ""
"The 'gateway_external_network_id' option must be configured for this "
"agent as Neutron has more than one external network."
msgstr ""

#: neutron/agent/l3/agent.py:558
#: neutron/plugins/cisco/cfg_agent/service_helpers/routing_svc_helper.py:630
#, python-format
msgid "Router port %s has no IP address"
msgstr ""

#: neutron/agent/l3/ha.py:35
msgid "Location to store keepalived/conntrackd config files"
msgstr ""

#: neutron/agent/l3/ha.py:39
msgid "VRRP authentication type AH/PASS"
msgstr ""

#: neutron/agent/l3/ha.py:41
msgid "VRRP authentication password"
msgstr ""

#: neutron/agent/l3/ha.py:45
msgid "The advertisement interval in seconds"
msgstr ""

#: neutron/agent/l3/ha.py:56
#, python-format
msgid "Router %s is not a HA router"
msgstr ""

#: neutron/agent/l3/link_local_allocator.py:85
msgid "Cannot allocate link local address"
msgstr ""

#: neutron/agent/linux/async_process.py:67
msgid "respawn_interval must be >= 0 if provided."
msgstr ""

#: neutron/agent/linux/async_process.py:81
msgid "Process is already started"
msgstr ""

#: neutron/agent/linux/async_process.py:92
msgid "Process is not running."
msgstr ""

#: neutron/agent/linux/daemon.py:44
msgid "Unable to unlock pid file"
msgstr ""

#: neutron/agent/linux/dhcp.py:44
msgid "Location to store DHCP server config files"
msgstr ""

#: neutron/agent/linux/dhcp.py:47 neutron/plugins/vmware/dhcp_meta/nsx.py:45
msgid "Domain to use for building the hostnames"
msgstr ""

#: neutron/agent/linux/dhcp.py:50
msgid "Override the default dnsmasq settings with this file"
msgstr ""

#: neutron/agent/linux/dhcp.py:52
msgid "Comma-separated list of the DNS servers which will be used as forwarders."
msgstr ""

#: neutron/agent/linux/dhcp.py:56
msgid "Delete namespace after removing a dhcp server."
msgstr ""

#: neutron/agent/linux/dhcp.py:60
msgid "Limit number of leases to prevent a denial-of-service."
msgstr ""

#: neutron/agent/linux/dhcp.py:62
msgid "Use broadcast in DHCP replies"
msgstr ""

#: neutron/agent/linux/dhcp.py:259 neutron/agent/linux/utils.py:153
#, python-format
msgid "Error while reading %s"
msgstr ""

#: neutron/agent/linux/dhcp.py:266 neutron/agent/linux/utils.py:160
#, python-format
msgid "Unable to convert value in %s"
msgstr ""

#: neutron/agent/linux/dhcp.py:268 neutron/agent/linux/utils.py:162
#, python-format
msgid "Unable to access %s"
msgstr ""

#: neutron/agent/linux/external_process.py:32
msgid "Location to store child pid files"
msgstr ""

#: neutron/agent/linux/external_process.py:35
msgid "Action to be executed when a child process dies"
msgstr ""

#: neutron/agent/linux/external_process.py:37
msgid ""
"Interval between checks of child process liveness (seconds), use 0 to "
"disable"
msgstr ""

#: neutron/agent/linux/interface.py:39
msgid "Name of Open vSwitch bridge to use"
msgstr ""

#: neutron/agent/linux/interface.py:42
msgid "Uses veth for an interface or not"
msgstr ""

#: neutron/agent/linux/interface.py:44
msgid "MTU setting for device."
msgstr ""

#: neutron/agent/linux/interface.py:46
msgid ""
"Mapping between flavor and LinuxInterfaceDriver. It is specific to "
"MetaInterfaceDriver used with admin_user, admin_password, "
"admin_tenant_name, admin_url, auth_strategy, auth_region and "
"endpoint_type."
msgstr ""

#: neutron/agent/linux/interface.py:52
msgid "Admin username"
msgstr ""

#: neutron/agent/linux/interface.py:54 neutron/agent/metadata/agent.py:70
#: neutron/plugins/metaplugin/common/config.py:65
msgid "Admin password"
msgstr ""

#: neutron/agent/linux/interface.py:57 neutron/agent/metadata/agent.py:73
#: neutron/plugins/metaplugin/common/config.py:68
msgid "Admin tenant name"
msgstr ""

#: neutron/agent/linux/interface.py:59 neutron/agent/metadata/agent.py:75
#: neutron/plugins/metaplugin/common/config.py:70
msgid "Authentication URL"
msgstr ""

#: neutron/agent/linux/interface.py:61 neutron/agent/metadata/agent.py:77
#: neutron/common/config.py:47 neutron/plugins/metaplugin/common/config.py:72
msgid "The type of authentication to use"
msgstr ""

#: neutron/agent/linux/interface.py:63 neutron/agent/metadata/agent.py:79
#: neutron/plugins/metaplugin/common/config.py:74
msgid "Authentication region"
msgstr ""

#: neutron/agent/linux/interface.py:66 neutron/agent/metadata/agent.py:89
msgid "Network service endpoint type to pull from the keystone catalog"
msgstr ""

#: neutron/agent/linux/ip_lib.py:28
msgid "Force ip_lib calls to use the root helper"
msgstr ""

#: neutron/agent/linux/ip_link_support.py:32
#, python-format
msgid "ip link command is not supported: %(reason)s"
msgstr ""

#: neutron/agent/linux/ip_link_support.py:36
#, python-format
msgid "ip link capability %(capability)s is not supported"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:198
#, python-format
msgid "Unknown chain: %r"
msgstr ""

#: neutron/agent/linux/keepalived.py:36
#, python-format
msgid "Invalid instance state: %%(state)s, valid states are: %(valid_states)s"
msgstr ""

#: neutron/agent/linux/keepalived.py:42
#, python-format
msgid ""
"Invalid notify state: %%(state)s, valid states are: "
"%(valid_notify_states)s"
msgstr ""

#: neutron/agent/linux/keepalived.py:48
#, python-format
msgid ""
"Invalid authentication type: %%(auth_type)s, valid types are: "
"%(valid_auth_types)s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:39
msgid "Timeout in seconds for ovs-vsctl commands"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:454
#, python-format
msgid "Unable to determine mac address for %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:578
msgid "Cannot match priority on flow deletion or modification"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:583
msgid "Must specify one or more actions on flow addition or modification"
msgstr ""

#: neutron/agent/linux/ra.py:31
msgid "Location to store IPv6 RA config files"
msgstr ""

#: neutron/agent/linux/utils.py:68
#, python-format
msgid ""
"\n"
"Command: %(cmd)s\n"
"Exit code: %(code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: neutron/agent/metadata/agent.py:68
#: neutron/plugins/metaplugin/common/config.py:63
msgid "Admin user"
msgstr ""

#: neutron/agent/metadata/agent.py:82
msgid "Turn off verification of the certificate for ssl"
msgstr ""

#: neutron/agent/metadata/agent.py:85
msgid "Certificate Authority public key (CA cert) file for ssl"
msgstr ""

#: neutron/agent/metadata/agent.py:92
msgid "IP address used by Nova metadata server."
msgstr ""

#: neutron/agent/metadata/agent.py:95
msgid "TCP Port used by Nova metadata server."
msgstr ""

#: neutron/agent/metadata/agent.py:98
#: neutron/plugins/vmware/dhcp_meta/nsx.py:64
msgid "Shared secret to sign instance-id request"
msgstr ""

#: neutron/agent/metadata/agent.py:103
msgid "Protocol to access nova metadata, http or https"
msgstr ""

#: neutron/agent/metadata/agent.py:105
msgid "Allow to perform insecure SSL (https) requests to nova metadata"
msgstr ""

#: neutron/agent/metadata/agent.py:109
msgid "Client certificate for nova metadata api server."
msgstr ""

#: neutron/agent/metadata/agent.py:112
msgid "Private key of client certificate."
msgstr ""

#: neutron/agent/metadata/agent.py:157
#: neutron/agent/metadata/namespace_proxy.py:76
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: neutron/agent/metadata/agent.py:236
msgid ""
"Either one of parameter network_id or router_id must be passed to "
"_get_ports method."
msgstr ""

#: neutron/agent/metadata/agent.py:298
#: neutron/agent/metadata/namespace_proxy.py:121
msgid "Remote metadata server experienced an internal server error."
msgstr ""

#: neutron/agent/metadata/agent.py:304
#: neutron/agent/metadata/namespace_proxy.py:127
#, python-format
msgid "Unexpected response code: %s"
msgstr ""

#: neutron/agent/metadata/agent.py:356
msgid "Location for Metadata Proxy UNIX domain socket"
msgstr ""

#: neutron/agent/metadata/agent.py:359
msgid "Number of separate worker processes for metadata server"
msgstr ""

#: neutron/agent/metadata/agent.py:363
msgid "Number of backlog requests to configure the metadata server socket with"
msgstr ""

#: neutron/agent/metadata/namespace_proxy.py:62
msgid "network_id and router_id are None. One must be provided."
msgstr ""

#: neutron/agent/metadata/namespace_proxy.py:150
msgid "Network that will have instance metadata proxied."
msgstr ""

#: neutron/agent/metadata/namespace_proxy.py:153
msgid "Router that will have connected instances' metadata proxied."
msgstr ""

#: neutron/agent/metadata/namespace_proxy.py:156
#: neutron/tests/functional/agent/linux/simple_daemon.py:42
msgid "Location of pid file of this process."
msgstr ""

#: neutron/agent/metadata/namespace_proxy.py:159
msgid "Run as daemon."
msgstr ""

#: neutron/agent/metadata/namespace_proxy.py:162
msgid "TCP Port to listen for metadata server requests."
msgstr ""

#: neutron/api/api_common.py:116
#, python-format
msgid "Limit must be an integer 0 or greater and not '%d'"
msgstr ""

#: neutron/api/api_common.py:133
msgid "The number of sort_keys and sort_dirs must be same"
msgstr ""

#: neutron/api/api_common.py:138
#, python-format
msgid "%s is invalid attribute for sort_keys"
msgstr ""

#: neutron/api/api_common.py:142
#, python-format
msgid ""
"%(invalid_dirs)s is invalid value for sort_dirs, valid value is '%(asc)s'"
" and '%(desc)s'"
msgstr ""

#: neutron/api/api_common.py:316 neutron/api/v2/base.py:602
#, python-format
msgid "Unable to find '%s' in request body"
msgstr ""

#: neutron/api/api_common.py:323
#, python-format
msgid "Failed to parse request. Parameter '%s' not specified"
msgstr ""

#: neutron/api/extensions.py:253
#, python-format
msgid "Extension with alias %s does not exist"
msgstr ""

#: neutron/api/extensions.py:257 neutron/api/extensions.py:261
msgid "Resource not found."
msgstr ""

#: neutron/api/versions.py:45
msgid "Unknown API version specified"
msgstr ""

#: neutron/api/rpc/handlers/dhcp_rpc.py:66
msgid "Unrecognized action"
msgstr ""

#: neutron/api/v2/attributes.py:44
#, python-format
msgid ""
"Invalid input. '%(target_dict)s' must be a dictionary with keys: "
"%(expected_keys)s"
msgstr ""

#: neutron/api/v2/attributes.py:55
#, python-format
msgid ""
"Validation of dictionary's keys failed.Expected keys: %(expected_keys)s "
"Provided keys: %(provided_keys)s"
msgstr ""

#: neutron/api/v2/attributes.py:69
#, python-format
msgid "'%(data)s' is not in %(valid_values)s"
msgstr ""

#: neutron/api/v2/attributes.py:85
#, python-format
msgid "'%s' Blank strings are not permitted"
msgstr ""

#: neutron/api/v2/attributes.py:95
#, python-format
msgid "'%s' is not a valid string"
msgstr ""

#: neutron/api/v2/attributes.py:100
#, python-format
msgid "'%(data)s' exceeds maximum length of %(max_len)s"
msgstr ""

#: neutron/api/v2/attributes.py:110
#, python-format
msgid "'%s' is not a valid boolean value"
msgstr ""

#: neutron/api/v2/attributes.py:129 neutron/api/v2/attributes.py:498
#, python-format
msgid "'%s' is not an integer"
msgstr ""

#: neutron/api/v2/attributes.py:133
#, python-format
msgid "'%(data)s' is too small - must be at least '%(limit)d'"
msgstr ""

#: neutron/api/v2/attributes.py:138
#, python-format
msgid "'%(data)s' is too large - must be no larger than '%(limit)d'"
msgstr ""

#: neutron/api/v2/attributes.py:147
#, python-format
msgid "'%s' contains whitespace"
msgstr ""

#: neutron/api/v2/attributes.py:162
#, python-format
msgid "'%s' is not a valid MAC address"
msgstr ""

#: neutron/api/v2/attributes.py:177
#, python-format
msgid "'%s' is not a valid IP address"
msgstr ""

#: neutron/api/v2/attributes.py:188
#, python-format
msgid "Invalid data format for IP pool: '%s'"
msgstr ""

#: neutron/api/v2/attributes.py:207 neutron/api/v2/attributes.py:214
#, python-format
msgid "Invalid data format for fixed IP: '%s'"
msgstr ""

#: neutron/api/v2/attributes.py:222
#, python-format
msgid "Duplicate IP address '%s'"
msgstr ""

#: neutron/api/v2/attributes.py:243
#, python-format
msgid "%(host)s is not a valid IP or hostname. Details: %(ip_err)s, %(name_err)s"
msgstr ""

#: neutron/api/v2/attributes.py:251
#, python-format
msgid "Invalid data format for nameserver: '%s'"
msgstr ""

#: neutron/api/v2/attributes.py:260
#, python-format
msgid "'%(host)s' is not a valid nameserver. %(msg)s"
msgstr ""

#: neutron/api/v2/attributes.py:264
#, python-format
msgid "Duplicate nameserver '%s'"
msgstr ""

#: neutron/api/v2/attributes.py:272
#, python-format
msgid "Invalid data format for hostroute: '%s'"
msgstr ""

#: neutron/api/v2/attributes.py:292
#, python-format
msgid "Duplicate hostroute '%s'"
msgstr ""

#: neutron/api/v2/attributes.py:309 neutron/tests/unit/test_attributes.py:497
#: neutron/tests/unit/test_attributes.py:511
#: neutron/tests/unit/test_attributes.py:519
#, python-format
msgid "'%(data)s' isn't a recognized IP subnet cidr, '%(cidr)s' is recommended"
msgstr ""

#: neutron/api/v2/attributes.py:315
#, python-format
msgid "'%s' is not a valid IP subnet"
msgstr ""

#: neutron/api/v2/attributes.py:323 neutron/api/v2/attributes.py:411
#, python-format
msgid "'%s' is not a list"
msgstr ""

#: neutron/api/v2/attributes.py:328 neutron/api/v2/attributes.py:422
#, python-format
msgid "Duplicate items in the list: '%s'"
msgstr ""

#: neutron/api/v2/attributes.py:356
#, python-format
msgid "'%s' exceeds the 255 character hostname limit"
msgstr ""

#: neutron/api/v2/attributes.py:360
msgid "Encountered an empty component."
msgstr ""

#: neutron/api/v2/attributes.py:363
#, python-format
msgid "Name '%s' must not start or end with a hyphen."
msgstr ""

#: neutron/api/v2/attributes.py:366
#, python-format
msgid ""
"Name '%s' must be 1-63 characters long, each of which can only be "
"alphanumeric or a hyphen."
msgstr ""

#: neutron/api/v2/attributes.py:371
#, python-format
msgid "TLD '%s' must not be all numeric"
msgstr ""

#: neutron/api/v2/attributes.py:373
#, python-format
msgid "'%(data)s' is not a valid hostname. Reason: %(reason)s"
msgstr ""

#: neutron/api/v2/attributes.py:386
#, python-format
msgid "'%s' is not a valid input"
msgstr ""

#: neutron/api/v2/attributes.py:399
#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:532
#, python-format
msgid "'%s' is not a valid UUID"
msgstr ""

#: neutron/api/v2/attributes.py:442
#, python-format
msgid "Validator '%s' does not exist."
msgstr ""

#: neutron/api/v2/attributes.py:452
#, python-format
msgid "'%s' is not a dictionary"
msgstr ""

#: neutron/api/v2/attributes.py:503
#, python-format
msgid "'%s' should be non-negative"
msgstr ""

#: neutron/api/v2/attributes.py:522
#, python-format
msgid "'%s' cannot be converted to boolean"
msgstr ""

#: neutron/api/v2/attributes.py:535
#: neutron/plugins/nec/extensions/packetfilter.py:72
#, python-format
msgid "'%s' is not a integer"
msgstr ""

#: neutron/api/v2/attributes.py:548
#, python-format
msgid "'%s' is not of the form <key>=[value]"
msgstr ""

#: neutron/api/v2/base.py:90
msgid "Native pagination depend on native sorting"
msgstr ""

#: neutron/api/v2/base.py:496
#, python-format
msgid "Invalid format: %s"
msgstr ""

#: neutron/api/v2/base.py:557
msgid ""
"Specifying 'tenant_id' other than authenticated tenant in request "
"requires admin privileges"
msgstr ""

#: neutron/api/v2/base.py:565
msgid "Running without keystone AuthN requires  that tenant_id is specified"
msgstr ""

#: neutron/api/v2/base.py:583
msgid "Resource body required"
msgstr ""

#: neutron/api/v2/base.py:588
msgid "Bulk operation not supported"
msgstr ""

#: neutron/api/v2/base.py:591
msgid "Resources required"
msgstr ""

#: neutron/api/v2/base.py:613
#, python-format
msgid "Failed to parse request. Required attribute '%s' not specified"
msgstr ""

#: neutron/api/v2/base.py:620
#, python-format
msgid "Attribute '%s' not allowed in POST"
msgstr ""

#: neutron/api/v2/base.py:625
#, python-format
msgid "Cannot update read-only attribute %s"
msgstr ""

#: neutron/api/v2/base.py:643
#, python-format
msgid "Invalid input for %(attr)s. Reason: %(reason)s."
msgstr ""

#: neutron/api/v2/base.py:652 neutron/extensions/allowedaddresspairs.py:75
#: neutron/extensions/multiprovidernet.py:45
#, python-format
msgid "Unrecognized attribute(s) '%s'"
msgstr ""

#: neutron/api/v2/base.py:671
#, python-format
msgid "Tenant %(tenant_id)s not allowed to create %(resource)s on this network"
msgstr ""

#: neutron/api/v2/resource.py:127
#: neutron/tests/unit/test_api_v2_resource.py:250
msgid "Request Failed: internal server error while processing your request."
msgstr ""

#: neutron/cmd/sanity_check.py:89
msgid "Check for vxlan support"
msgstr ""

#: neutron/cmd/sanity_check.py:91
msgid "Check for patch port support"
msgstr ""

#: neutron/cmd/sanity_check.py:93
msgid "Check for nova notification support"
msgstr ""

#: neutron/cmd/sanity_check.py:95
msgid "Check for ARP responder support"
msgstr ""

#: neutron/cmd/sanity_check.py:97
msgid "Check for VF management support"
msgstr ""

#: neutron/common/config.py:39
msgid "The host IP to bind to"
msgstr ""

#: neutron/common/config.py:41
msgid "The port to bind to"
msgstr ""

#: neutron/common/config.py:43
msgid "The API paste config file to use"
msgstr ""

#: neutron/common/config.py:45
msgid "The path for API extensions"
msgstr ""

#: neutron/common/config.py:49
msgid "The core plugin Neutron will use"
msgstr ""

#: neutron/common/config.py:51 neutron/db/migration/cli.py:33
msgid "The service plugins Neutron will use"
msgstr ""

#: neutron/common/config.py:53
msgid "The base MAC address Neutron will use for VIFs"
msgstr ""

#: neutron/common/config.py:55
msgid "How many times Neutron will retry MAC generation"
msgstr ""

#: neutron/common/config.py:57
msgid "Allow the usage of the bulk API"
msgstr ""

#: neutron/common/config.py:59
msgid "Allow the usage of the pagination"
msgstr ""

#: neutron/common/config.py:61
msgid "Allow the usage of the sorting"
msgstr ""

#: neutron/common/config.py:63
msgid ""
"The maximum number of items returned in a single response, value was "
"'infinite' or negative integer means no limit"
msgstr ""

#: neutron/common/config.py:67
msgid "Maximum number of DNS nameservers"
msgstr ""

#: neutron/common/config.py:69
msgid "Maximum number of host routes per subnet"
msgstr ""

#: neutron/common/config.py:71
msgid "Maximum number of fixed ips per port"
msgstr ""

#: neutron/common/config.py:74
msgid ""
"DHCP lease duration (in seconds). Use -1 to tell dnsmasq to use infinite "
"lease times."
msgstr ""

#: neutron/common/config.py:77
msgid "Allow sending resource operation notification to DHCP agent"
msgstr ""

#: neutron/common/config.py:80
msgid "Allow overlapping IP support in Neutron"
msgstr ""

#: neutron/common/config.py:82
msgid "The hostname Neutron is running on"
msgstr ""

#: neutron/common/config.py:84
msgid ""
"Ensure that configured gateway is on subnet. For IPv6, validate only if "
"gateway is not a link local address. Deprecated, to be removed during the"
" K release, at which point the check will be mandatory."
msgstr ""

#: neutron/common/config.py:90
msgid "Send notification to nova when port status changes"
msgstr ""

#: neutron/common/config.py:92
msgid ""
"Send notification to nova when port data (fixed_ips/floatingip) changes "
"so nova can update its cache."
msgstr ""

#: neutron/common/config.py:96
msgid "URL for connection to nova"
msgstr ""

#: neutron/common/config.py:98
msgid "Username for connecting to nova in admin context"
msgstr ""

#: neutron/common/config.py:100
msgid "Password for connection to nova in admin context"
msgstr ""

#: neutron/common/config.py:103
msgid "The uuid of the admin nova tenant"
msgstr ""

#: neutron/common/config.py:105
msgid "The name of the admin nova tenant"
msgstr ""

#: neutron/common/config.py:108
msgid "Authorization URL for connecting to nova in admin context"
msgstr ""

#: neutron/common/config.py:111
msgid "CA file for novaclient to verify server certificates"
msgstr ""

#: neutron/common/config.py:113
msgid "If True, ignore any SSL validation issues"
msgstr ""

#: neutron/common/config.py:115
msgid ""
"Name of nova region to use. Useful if keystone manages more than one "
"region."
msgstr ""

#: neutron/common/config.py:118
msgid ""
"Number of seconds between sending events to nova if there are any events "
"to send."
msgstr ""

#: neutron/common/config.py:125
msgid ""
"Where to store Neutron state files. This directory must be writable by "
"the agent."
msgstr ""

#: neutron/common/config.py:158
#, python-format
msgid "Base MAC: %s"
msgstr ""

#: neutron/common/config.py:191
#, python-format
msgid "Unable to load %(app_name)s from configuration file %(config_path)s."
msgstr ""

#: neutron/common/exceptions.py:30
#: neutron/plugins/vmware/api_client/exception.py:27
msgid "An unknown exception occurred."
msgstr ""

#: neutron/common/exceptions.py:51
#, python-format
msgid "Bad %(resource)s request: %(msg)s"
msgstr ""

#: neutron/common/exceptions.py:63
msgid "Not authorized."
msgstr ""

#: neutron/common/exceptions.py:67
msgid "The service is unavailable"
msgstr ""

#: neutron/common/exceptions.py:71
#, python-format
msgid "User does not have admin privileges: %(reason)s"
msgstr ""

#: neutron/common/exceptions.py:75
#, python-format
msgid "Network %(net_id)s could not be found"
msgstr ""

#: neutron/common/exceptions.py:79
#, python-format
msgid "Subnet %(subnet_id)s could not be found"
msgstr ""

#: neutron/common/exceptions.py:83
#, python-format
msgid "Port %(port_id)s could not be found"
msgstr ""

#: neutron/common/exceptions.py:87
#, python-format
msgid "Port %(port_id)s could not be found on network %(net_id)s"
msgstr ""

#: neutron/common/exceptions.py:92
msgid "Policy configuration policy.json could not be found"
msgstr ""

#: neutron/common/exceptions.py:96
#, python-format
msgid "Failed to init policy %(policy)s because %(reason)s"
msgstr ""

#: neutron/common/exceptions.py:100
#, python-format
msgid "Failed to check policy %(policy)s because %(reason)s"
msgstr ""

#: neutron/common/exceptions.py:104
#, python-format
msgid "Unsupported port state: %(port_state)s"
msgstr ""

#: neutron/common/exceptions.py:108
msgid "The resource is inuse"
msgstr ""

#: neutron/common/exceptions.py:112
#, python-format
msgid ""
"Unable to complete operation on network %(net_id)s. There are one or more"
" ports still in use on the network."
msgstr ""

#: neutron/common/exceptions.py:117
#, python-format
msgid ""
"Unable to complete operation on subnet %(subnet_id)s. One or more ports "
"have an IP allocation from this subnet."
msgstr ""

#: neutron/common/exceptions.py:122
#, python-format
msgid ""
"Unable to complete operation on port %(port_id)s for network %(net_id)s. "
"Port already has an attacheddevice %(device_id)s."
msgstr ""

#: neutron/common/exceptions.py:128
#, python-format
msgid ""
"Unable to complete operation for network %(net_id)s. The mac address "
"%(mac)s is in use."
msgstr ""

#: neutron/common/exceptions.py:134
#, python-format
msgid ""
"Unable to complete operation for %(subnet_id)s. The number of host routes"
" exceeds the limit %(quota)s."
msgstr ""

#: neutron/common/exceptions.py:140
#, python-format
msgid ""
"Unable to complete operation for %(subnet_id)s. The number of DNS "
"nameservers exceeds the limit %(quota)s."
msgstr ""

#: neutron/common/exceptions.py:145
#, python-format
msgid ""
"Unable to complete operation for network %(net_id)s. The IP address "
"%(ip_address)s is in use."
msgstr ""

#: neutron/common/exceptions.py:150
#, python-format
msgid ""
"Unable to create the network. The VLAN %(vlan_id)s on physical network "
"%(physical_network)s is in use."
msgstr ""

#: neutron/common/exceptions.py:156
#, python-format
msgid ""
"Unable to create the flat network. Physical network %(physical_network)s "
"is in use."
msgstr ""

#: neutron/common/exceptions.py:161
#, python-format
msgid "Unable to create the network. The tunnel ID %(tunnel_id)s is in use."
msgstr ""

#: neutron/common/exceptions.py:166
msgid "Tenant network creation is not enabled."
msgstr ""

#: neutron/common/exceptions.py:174
msgid ""
"Unable to create the network. No tenant network is available for "
"allocation."
msgstr ""

#: neutron/common/exceptions.py:179
msgid ""
"Unable to create the network. No available network found in maximum "
"allowed attempts."
msgstr ""

#: neutron/common/exceptions.py:184
#, python-format
msgid ""
"Subnet on port %(port_id)s does not match the requested subnet "
"%(subnet_id)s"
msgstr ""

#: neutron/common/exceptions.py:189
#, python-format
msgid "Malformed request body: %(reason)s"
msgstr ""

#: neutron/common/exceptions.py:199
#, python-format
msgid "Invalid input for operation: %(error_message)s."
msgstr ""

#: neutron/common/exceptions.py:203
#, python-format
msgid "The allocation pool %(pool)s is not valid."
msgstr ""

#: neutron/common/exceptions.py:207
#, python-format
msgid ""
"Found overlapping allocation pools:%(pool_1)s %(pool_2)s for subnet "
"%(subnet_cidr)s."
msgstr ""

#: neutron/common/exceptions.py:212
#, python-format
msgid "The allocation pool %(pool)s spans beyond the subnet cidr %(subnet_cidr)s."
msgstr ""

#: neutron/common/exceptions.py:217
#, python-format
msgid "Unable to generate unique mac on network %(net_id)s."
msgstr ""

#: neutron/common/exceptions.py:221
#, python-format
msgid "No more IP addresses available on network %(net_id)s."
msgstr ""

#: neutron/common/exceptions.py:225
#, python-format
msgid "Bridge %(bridge)s does not exist."
msgstr ""

#: neutron/common/exceptions.py:229
#, python-format
msgid "Creation failed. %(dev_name)s already exists."
msgstr ""

#: neutron/common/exceptions.py:233
msgid "Sudo privilege is required to run this command."
msgstr ""

#: neutron/common/exceptions.py:237
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: neutron/common/exceptions.py:241
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr ""

#: neutron/common/exceptions.py:245
msgid "Tenant-id was missing from Quota request"
msgstr ""

#: neutron/common/exceptions.py:249
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"
msgstr ""

#: neutron/common/exceptions.py:254
#, python-format
msgid ""
"Unable to reconfigure sharing settings for network %(network)s. Multiple "
"tenants are using it"
msgstr ""

#: neutron/common/exceptions.py:259
#, python-format
msgid "Invalid extension environment: %(reason)s"
msgstr ""

#: neutron/common/exceptions.py:263
#, python-format
msgid "Extensions not found: %(extensions)s"
msgstr ""

#: neutron/common/exceptions.py:267
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: neutron/common/exceptions.py:271
#, python-format
msgid "Unable to find any IP address on external network %(net_id)s."
msgstr ""

#: neutron/common/exceptions.py:276
msgid "More than one external network exists"
msgstr ""

#: neutron/common/exceptions.py:280
#, python-format
msgid "An invalid value was provided for %(opt_name)s: %(opt_value)s"
msgstr ""

#: neutron/common/exceptions.py:285
#, python-format
msgid "Gateway ip %(ip_address)s conflicts with allocation pool %(pool)s"
msgstr ""

#: neutron/common/exceptions.py:290
#, python-format
msgid ""
"Current gateway ip %(ip_address)s already in use by port %(port_id)s. "
"Unable to update."
msgstr ""

#: neutron/common/exceptions.py:295
#, python-format
msgid "Invalid network VLAN range: '%(vlan_range)s' - '%(error)s'"
msgstr ""

#: neutron/common/exceptions.py:305
msgid "Empty physical network name."
msgstr ""

#: neutron/common/exceptions.py:309
#, python-format
msgid "Invalid network Tunnel range: '%(tunnel_range)s' - %(error)s"
msgstr ""

#: neutron/common/exceptions.py:320
#, python-format
msgid "Invalid network VXLAN port range: '%(vxlan_range)s'"
msgstr ""

#: neutron/common/exceptions.py:324
msgid "VXLAN Network unsupported."
msgstr ""

#: neutron/common/exceptions.py:328
#, python-format
msgid "Found duplicate extension: %(alias)s"
msgstr ""

#: neutron/common/exceptions.py:332
#, python-format
msgid ""
"The following device_id %(device_id)s is not owned by your tenant or "
"matches another tenants router."
msgstr ""

#: neutron/common/exceptions.py:337
#, python-format
msgid "Invalid CIDR %(input)s given as IP prefix"
msgstr ""

#: neutron/common/exceptions.py:341
#, python-format
msgid "Router '%(router_id)s' is not compatible with this agent"
msgstr ""

#: neutron/common/ipv6_utils.py:36
msgid "Unable to generate IP address by EUI64 for IPv4 prefix"
msgstr ""

#: neutron/common/ipv6_utils.py:43
#, python-format
msgid ""
"Bad prefix or mac format for generating IPv6 address by EUI-64: "
"%(prefix)s, %(mac)s:"
msgstr ""

#: neutron/common/ipv6_utils.py:47
#, python-format
msgid "Bad prefix type for generate IPv6 address by EUI-64: %s"
msgstr ""

#: neutron/common/utils.py:201
#: neutron/plugins/sriovnicagent/common/config.py:36
#, python-format
msgid "Invalid mapping: '%s'"
msgstr ""

#: neutron/common/utils.py:204
#: neutron/plugins/sriovnicagent/common/config.py:39
#, python-format
msgid "Missing key in mapping: '%s'"
msgstr ""

#: neutron/common/utils.py:207
#, python-format
msgid "Missing value in mapping: '%s'"
msgstr ""

#: neutron/common/utils.py:209
#, python-format
msgid "Key %(key)s in mapping: '%(mapping)s' not unique"
msgstr ""

#: neutron/common/utils.py:212
#, python-format
msgid "Value %(value)s in mapping: '%(mapping)s' not unique"
msgstr ""

#: neutron/db/agents_db.py:38
msgid ""
"Seconds to regard the agent is down; should be at least twice "
"report_interval, to be sure the agent is down for good."
msgstr ""

#: neutron/db/agentschedulers_db.py:37
msgid "Driver to use for scheduling network to DHCP agent"
msgstr ""

#: neutron/db/agentschedulers_db.py:39
msgid "Allow auto scheduling networks to DHCP agent."
msgstr ""

#: neutron/db/agentschedulers_db.py:41
msgid "Number of DHCP agents scheduled to host a network."
msgstr ""

#: neutron/db/common_db_mixin.py:122
msgid "Cannot create resource for another tenant"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:407
msgid "IP allocation requires subnet_id or ip_address"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:419
#, python-format
msgid "IP address %s is not a valid IP for the defined networks subnets"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:425
#, python-format
msgid ""
"Failed to create port on network %(network_id)s, because fixed_ips "
"included invalid subnet %(subnet_id)s"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:445
#, python-format
msgid "IP address %s is not a valid IP for the defined subnet"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:451
#, python-format
msgid ""
"IPv6 address %(address)s can not be directly assigned to a port on subnet"
" %(id)s with %(mode)s address mode"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:463 neutron/db/db_base_plugin_v2.py:505
#: neutron/plugins/opencontrail/contrail_plugin.py:388
msgid "Exceeded maximim amount of fixed ips per port"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:604
msgid "0 is not allowed as CIDR prefix length"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:614
#, python-format
msgid ""
"Requested subnet with cidr: %(cidr)s for network: %(network_id)s overlaps"
" with another subnet"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:699 neutron/db/db_base_plugin_v2.py:703
#, python-format
msgid "Invalid route: %s"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:781
#, python-format
msgid ""
"Invalid CIDR %s for IPv6 address mode. OpenStack uses the EUI-64 address "
"format, which requires the prefix to be /64."
msgstr ""

#: neutron/db/db_base_plugin_v2.py:789
#, python-format
msgid ""
"ipv6_ra_mode set to '%(ra_mode)s' with ipv6_address_mode set to "
"'%(addr_mode)s' is not valid. If both attributes are set, they must be "
"the same value"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:797
msgid ""
"ipv6_ra_mode or ipv6_address_mode cannot be set when enable_dhcp is set "
"to False."
msgstr ""

#: neutron/db/db_base_plugin_v2.py:803
msgid "Cannot disable enable_dhcp with ipv6 attributes set"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:994
#, python-format
msgid "%(name)s '%(addr)s' does not match the ip_version '%(ip_version)s'"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:1018
msgid "Gateway is not valid on subnet"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:1038 neutron/db/db_base_plugin_v2.py:1052
#: neutron/plugins/opencontrail/contrail_plugin.py:312
msgid "new subnet"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:1045
#, python-format
msgid "Error parsing dns address %s"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:1061
msgid "ipv6_ra_mode is not valid when ip_version is 4"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:1065
msgid "ipv6_address_mode is not valid when ip_version is 4"
msgstr ""

#: neutron/db/dvr_mac_db.py:37
msgid "The base mac address used for unique DVR instances by Neutron"
msgstr ""

#: neutron/db/extraroute_db.py:36
msgid "Maximum number of routes"
msgstr ""

#: neutron/db/extraroute_db.py:91
msgid "the nexthop is not connected with router"
msgstr ""

#: neutron/db/extraroute_db.py:96
msgid "the nexthop is used by router"
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:49
msgid "Driver to use for scheduling router to a default L3 agent"
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:52
msgid "Allow auto scheduling of routers to L3 agent."
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:54
msgid ""
"Automatically reschedule routers from offline L3 agents to online L3 "
"agents."
msgstr ""

#: neutron/db/l3_db.py:263
#, python-format
msgid "No eligible l3 agent associated with external network %s found"
msgstr ""

#: neutron/db/l3_db.py:284
#, python-format
msgid "No IPs available for external network %s"
msgstr ""

#: neutron/db/l3_db.py:304
#, python-format
msgid "Network %s is not an external network"
msgstr ""

#: neutron/db/l3_db.py:411
#, python-format
msgid "Router already has a port on subnet %s"
msgstr ""

#: neutron/db/l3_db.py:425
#, python-format
msgid ""
"Cidr %(subnet_cidr)s of subnet %(subnet_id)s overlaps with cidr %(cidr)s "
"of subnet %(sub_id)s"
msgstr ""

#: neutron/db/l3_db.py:441 neutron/db/l3_db.py:593 neutron/db/l3_dvr_db.py:254
#: neutron/plugins/bigswitch/l3_router_plugin.py:176
#: neutron/plugins/bigswitch/l3_router_plugin.py:185
#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:182
#: neutron/plugins/opencontrail/contrail_plugin.py:499
msgid "Either subnet_id or port_id must be specified"
msgstr ""

#: neutron/db/l3_db.py:444 neutron/plugins/opencontrail/contrail_plugin.py:509
msgid "Cannot specify both subnet-id and port-id"
msgstr ""

#: neutron/db/l3_db.py:457
msgid "Router port must have exactly one fixed IP"
msgstr ""

#: neutron/db/l3_db.py:472
msgid "Subnet for router interface must have a gateway IP"
msgstr ""

#: neutron/db/l3_db.py:641 neutron/plugins/nec/nec_router.py:197
#, python-format
msgid "Cannot add floating IP to port on subnet %s which has no gateway_ip"
msgstr ""

#: neutron/db/l3_db.py:677
#, python-format
msgid ""
"Port %(port_id)s is associated with a different tenant than Floating IP "
"%(floatingip_id)s and therefore cannot be bound."
msgstr ""

#: neutron/db/l3_db.py:681
#, python-format
msgid ""
"Cannot create floating IP and bind it to Port %s, since that port is "
"owned by a different tenant."
msgstr ""

#: neutron/db/l3_db.py:693
#, python-format
msgid "Port %(id)s does not have fixed ip %(address)s"
msgstr ""

#: neutron/db/l3_db.py:700
#, python-format
msgid "Cannot add floating IP to port %s that hasno fixed IP addresses"
msgstr ""

#: neutron/db/l3_db.py:704
#, python-format
msgid ""
"Port %s has multiple fixed IPs.  Must provide a specific IP when "
"assigning a floating IP"
msgstr ""

#: neutron/db/l3_db.py:734 neutron/plugins/vmware/plugins/base.py:1825
msgid "fixed_ip_address cannot be specified without a port_id"
msgstr ""

#: neutron/db/l3_db.py:774
#, python-format
msgid "Network %s is not a valid external network"
msgstr ""

#: neutron/db/l3_dvr_db.py:43
msgid ""
"System-wide flag to determine the type of router that tenants can create."
" Only admin can override."
msgstr ""

#: neutron/db/l3_dvr_db.py:473
msgid "Unable to create the Agent Gateway Port"
msgstr ""

#: neutron/db/l3_dvr_db.py:506
msgid "Unable to create the SNAT Interface Port"
msgstr ""

#: neutron/db/l3_hamode_db.py:41
msgid "Enable HA mode for virtual routers."
msgstr ""

#: neutron/db/l3_hamode_db.py:44
msgid "Maximum number of agents on which a router will be scheduled."
msgstr ""

#: neutron/db/l3_hamode_db.py:48
msgid "Minimum number of agents on which a router will be scheduled."
msgstr ""

#: neutron/db/l3_hamode_db.py:52
msgid "Subnet used for the l3 HA admin network."
msgstr ""

#: neutron/db/routedserviceinsertion_db.py:34
#, python-format
msgid "Resource type '%(resource_type)s' is longer than %(maxlen)d characters"
msgstr ""

#: neutron/db/securitygroups_db.py:513
msgid "Default security group"
msgstr ""

#: neutron/db/securitygroups_rpc_base.py:59
#, python-format
msgid "%s must implement get_port_from_device or get_ports_from_devices."
msgstr ""

#: neutron/db/sqlalchemyutils.py:73
#, python-format
msgid "%s is invalid attribute for sort_key"
msgstr ""

#: neutron/db/sqlalchemyutils.py:76
#, python-format
msgid ""
"The attribute '%(attr)s' is reference to other resource, can't used by "
"sort '%(resource)s'"
msgstr ""

#: neutron/db/migration/__init__.py:40
#, python-format
msgid "%s cannot be called while in offline mode"
msgstr ""

#: neutron/db/migration/cli.py:30
msgid "Neutron plugin provider module"
msgstr ""

#: neutron/db/migration/cli.py:39
msgid "Neutron quota driver class"
msgstr ""

#: neutron/db/migration/cli.py:47
msgid "URL to database"
msgstr ""

#: neutron/db/migration/cli.py:50
msgid "Database engine"
msgstr ""

#: neutron/db/migration/cli.py:73
msgid "You must provide a revision or relative delta"
msgstr ""

#: neutron/db/migration/cli.py:103 neutron/db/migration/cli.py:116
msgid "Timeline branches unable to generate timeline"
msgstr ""

#: neutron/db/migration/cli.py:110
msgid "HEAD file does not match migration timeline head"
msgstr ""

#: neutron/db/migration/cli.py:156
msgid "Available commands"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:90
msgid "Missing version in alembic_versions table"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:92
#, python-format
msgid "Multiple versions in alembic_versions table: %s"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:96
#, python-format
msgid ""
"Unsupported database schema %(current)s. Please migrate your database to "
"one of following versions: %(supported)s"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:425
#, python-format
msgid "Unknown tunnel type: %s"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:453
msgid "The plugin type whose database will be migrated"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:456
msgid "The connection url for the target db"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:459
#, python-format
msgid "The %s tunnel type to migrate from"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:462
#: neutron/plugins/openvswitch/common/config.py:67
msgid "The UDP port to use for VXLAN tunnels."
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:465
msgid "Retain the old plugin's tables"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:471
#, python-format
msgid ""
"Tunnel args (tunnel-type and vxlan-udp-port) are not valid for the %s "
"plugin"
msgstr ""

#: neutron/db/migration/migrate_to_ml2.py:478
#, python-format
msgid ""
"Support for migrating %(plugin)s for release %(release)s is not yet "
"implemented"
msgstr ""

#: neutron/debug/commands.py:33
msgid "Unimplemented commands"
msgstr ""

#: neutron/debug/commands.py:45
msgid "ID of network to probe"
msgstr ""

#: neutron/debug/commands.py:49
msgid "Owner type of the device: network/compute"
msgstr ""

#: neutron/debug/commands.py:57
#, python-format
msgid "Probe created : %s "
msgstr ""

#: neutron/debug/commands.py:69
msgid "ID of probe port to delete"
msgstr ""

#: neutron/debug/commands.py:76
#, python-format
msgid "Probe %s deleted"
msgstr ""

#: neutron/debug/commands.py:119
msgid "ID of probe port to execute command"
msgstr ""

#: neutron/debug/commands.py:124
msgid "Command to execute"
msgstr ""

#: neutron/debug/commands.py:144
msgid "Ping timeout"
msgstr ""

#: neutron/debug/commands.py:148
msgid "ID of network"
msgstr ""

#: neutron/debug/shell.py:61
msgid "Config file for interface driver (You may also use l3_agent.ini)"
msgstr ""

#: neutron/debug/shell.py:69
msgid ""
"You must provide a config file for bridge - either --config-file or "
"env[NEUTRON_TEST_CONFIG_FILE]"
msgstr ""

#: neutron/extensions/agent.py:61
#, python-format
msgid "Agent %(id)s could not be found"
msgstr ""

#: neutron/extensions/agent.py:65
#, python-format
msgid "Agent with agent_type=%(agent_type)s and host=%(host)s could not be found"
msgstr ""

#: neutron/extensions/agent.py:70
#, python-format
msgid "Multiple agents with agent_type=%(agent_type)s and host=%(host)s found"
msgstr ""

#: neutron/extensions/allowedaddresspairs.py:24
msgid "Maximum number of allowed address pairs"
msgstr ""

#: neutron/extensions/allowedaddresspairs.py:31
msgid "AllowedAddressPair must contain ip_address"
msgstr ""

#: neutron/extensions/allowedaddresspairs.py:35
msgid ""
"Port Security must be enabled in order to have allowed address pairs on a"
" port."
msgstr ""

#: neutron/extensions/allowedaddresspairs.py:40
#, python-format
msgid ""
"Request contains duplicate address pair: mac_address %(mac_address)s "
"ip_address %(ip_address)s."
msgstr ""

#: neutron/extensions/allowedaddresspairs.py:45
#, python-format
msgid "The number of allowed address pair exceeds the maximum %(quota)s."
msgstr ""

#: neutron/extensions/dhcpagentscheduler.py:127
#, python-format
msgid "Agent %(id)s is not a valid DHCP Agent or has been disabled"
msgstr ""

#: neutron/extensions/dhcpagentscheduler.py:131
#, python-format
msgid ""
"The network %(network_id)s has been already hosted by the DHCP Agent "
"%(agent_id)s."
msgstr ""

#: neutron/extensions/dhcpagentscheduler.py:136
#, python-format
msgid "The network %(network_id)s is not hosted by the DHCP agent %(agent_id)s."
msgstr ""

#: neutron/extensions/dvr.py:37
#, python-format
msgid "Distributed Virtual Router Mac Address for host %(host)s does not exist."
msgstr ""

#: neutron/extensions/dvr.py:42
#, python-format
msgid "Unable to generate unique DVR mac for host %(host)s."
msgstr ""

#: neutron/extensions/external_net.py:23
#, python-format
msgid ""
"External network %(net_id)s cannot be updated to be made non-external, "
"since it has existing gateway ports"
msgstr ""

#: neutron/extensions/external_net.py:51
msgid "Adds external network attribute to network resource."
msgstr ""

#: neutron/extensions/extra_dhcp_opt.py:23
#, python-format
msgid "ExtraDhcpOpt %(id)s could not be found"
msgstr ""

#: neutron/extensions/extra_dhcp_opt.py:27
#, python-format
msgid "Invalid data format for extra-dhcp-opt: %(data)s"
msgstr ""

#: neutron/extensions/extraroute.py:23
#, python-format
msgid "Invalid format for routes: %(routes)s, %(reason)s"
msgstr ""

#: neutron/extensions/extraroute.py:27
#, python-format
msgid ""
"Router interface for subnet %(subnet_id)s on router %(router_id)s cannot "
"be deleted, as it is required by one or more routes."
msgstr ""

#: neutron/extensions/extraroute.py:33
#, python-format
msgid ""
"Unable to complete operation for %(router_id)s. The number of routes "
"exceeds the maximum %(quota)s."
msgstr ""

#: neutron/extensions/firewall.py:35
#, python-format
msgid "Firewall %(firewall_id)s could not be found."
msgstr ""

#: neutron/extensions/firewall.py:39
#, python-format
msgid "Firewall %(firewall_id)s is still active."
msgstr ""

#: neutron/extensions/firewall.py:43
#, python-format
msgid ""
"Operation cannot be performed since associated Firewall %(firewall_id)s "
"is in %(pending_state)s."
msgstr ""

#: neutron/extensions/firewall.py:48
#, python-format
msgid "Firewall Policy %(firewall_policy_id)s could not be found."
msgstr ""

#: neutron/extensions/firewall.py:52
#, python-format
msgid "Firewall Policy %(firewall_policy_id)s is being used."
msgstr ""

#: neutron/extensions/firewall.py:62
#, python-format
msgid ""
"Operation cannot be performed since Firewall Policy "
"%(firewall_policy_id)s is shared but Firewall Rule %(firewall_rule_id)s "
"is not shared"
msgstr ""

#: neutron/extensions/firewall.py:74
#, python-format
msgid ""
"Operation cannot be performed. Before sharing Firewall Policy "
"%(firewall_policy_id)s, share associated Firewall Rule "
"%(firewall_rule_id)s"
msgstr ""

#: neutron/extensions/firewall.py:80
#, python-format
msgid "Firewall Rule %(firewall_rule_id)s could not be found."
msgstr ""

#: neutron/extensions/firewall.py:84
#, python-format
msgid "Firewall Rule %(firewall_rule_id)s is being used."
msgstr ""

#: neutron/extensions/firewall.py:88
#, python-format
msgid ""
"Firewall Rule %(firewall_rule_id)s is not associated  with Firewall "
"Policy %(firewall_policy_id)s."
msgstr ""

#: neutron/extensions/firewall.py:93
#, python-format
msgid ""
"Firewall Rule protocol %(protocol)s is not supported. Only protocol "
"values %(values)s and their integer representation (0 to 255) are "
"supported."
msgstr ""

#: neutron/extensions/firewall.py:99
#, python-format
msgid ""
"Firewall rule action %(action)s is not supported. Only action values "
"%(values)s are supported."
msgstr ""

#: neutron/extensions/firewall.py:104
#, python-format
msgid "%(param)s are not allowed when protocol is set to ICMP."
msgstr ""

#: neutron/extensions/firewall.py:109
msgid "Source/destination port requires a protocol"
msgstr ""

#: neutron/extensions/firewall.py:113
#, python-format
msgid "Invalid value for port %(port)s."
msgstr ""

#: neutron/extensions/firewall.py:117
msgid "Missing rule info argument for insert/remove rule operation."
msgstr ""

#: neutron/extensions/firewall.py:127
#, python-format
msgid "%(driver)s: Internal driver error."
msgstr ""

#: neutron/extensions/firewall.py:138
#, python-format
msgid ""
"Operation cannot be performed since Firewall Rule %(firewall_rule_id)s is"
" not shared and belongs to another tenant %(tenant_id)s"
msgstr ""

#: neutron/extensions/firewall.py:189
#, python-format
msgid "Port '%s' is not a valid number"
msgstr ""

#: neutron/extensions/firewall.py:193
#, python-format
msgid "Invalid port '%s'"
msgstr ""

#: neutron/extensions/firewall.py:207
#, python-format
msgid "%(msg_ip)s and %(msg_subnet)s"
msgstr ""

#: neutron/extensions/firewall.py:328
msgid "Number of firewalls allowed per tenant. A negative value means unlimited."
msgstr ""

#: neutron/extensions/firewall.py:332
msgid ""
"Number of firewall policies allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/extensions/firewall.py:336
msgid ""
"Number of firewall rules allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/extensions/l3.py:29
#, python-format
msgid "Router %(router_id)s could not be found"
msgstr ""

#: neutron/extensions/l3.py:33
#, python-format
msgid "Router %(router_id)s still has ports"
msgstr ""

#: neutron/extensions/l3.py:37
#, python-format
msgid "Router %(router_id)s does not have an interface with id %(port_id)s"
msgstr ""

#: neutron/extensions/l3.py:42
#, python-format
msgid "Router %(router_id)s has no interface on subnet %(subnet_id)s"
msgstr ""

#: neutron/extensions/l3.py:47
#, python-format
msgid ""
"Router interface for subnet %(subnet_id)s on router %(router_id)s cannot "
"be deleted, as it is required by one or more floating IPs."
msgstr ""

#: neutron/extensions/l3.py:53
#, python-format
msgid "Floating IP %(floatingip_id)s could not be found"
msgstr ""

#: neutron/extensions/l3.py:57
#, python-format
msgid ""
"External network %(external_network_id)s is not reachable from subnet "
"%(subnet_id)s.  Therefore, cannot associate Port %(port_id)s with a "
"Floating IP."
msgstr ""

#: neutron/extensions/l3.py:63
#, python-format
msgid ""
"Cannot associate floating IP %(floating_ip_address)s (%(fip_id)s) with "
"port %(port_id)s using fixed IP %(fixed_ip)s, as that fixed IP already "
"has a floating IP on external network %(net_id)s."
msgstr ""

#: neutron/extensions/l3.py:70
#, python-format
msgid ""
"Port %(port_id)s has owner %(device_owner)s and therefore cannot be "
"deleted directly via the port API."
msgstr ""

#: neutron/extensions/l3.py:75
#, python-format
msgid ""
"Gateway cannot be updated for router %(router_id)s, since a gateway to "
"external network %(net_id)s is required by one or more floating IPs."
msgstr ""

#: neutron/extensions/l3.py:151
msgid "Number of routers allowed per tenant. A negative value means unlimited."
msgstr ""

#: neutron/extensions/l3.py:155
msgid ""
"Number of floating IPs allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/extensions/l3_ext_ha_mode.py:33
msgid "Currenly distributed HA routers are not supported."
msgstr ""

#: neutron/extensions/l3_ext_ha_mode.py:38
#, python-format
msgid ""
"Failed to allocate a VRID in the network %(network_id)s for the router "
"%(router_id)s after %(max_tries)s tries."
msgstr ""

#: neutron/extensions/l3_ext_ha_mode.py:43
#, python-format
msgid ""
"No more Virtual Router Identifier (VRID) available when creating router "
"%(router_id)s. The limit of number of HA Routers per tenant is 254."
msgstr ""

#: neutron/extensions/l3_ext_ha_mode.py:49
#, python-format
msgid ""
"The HA Network CIDR specified in the configuration file isn't valid; "
"%(cidr)s."
msgstr ""

#: neutron/extensions/l3_ext_ha_mode.py:54
#, python-format
msgid ""
"Not enough l3 agents available to ensure HA. Minimum required "
"%(min_agents)s, available %(num_agents)s."
msgstr ""

#: neutron/extensions/l3_ext_ha_mode.py:59
#, python-format
msgid ""
"min_l3_agents_per_router config parameter is not valid. It has to be "
"equal to or more than %s for HA."
msgstr ""

#: neutron/extensions/l3agentscheduler.py:158
#, python-format
msgid "Agent %(id)s is not a L3 Agent or has been disabled"
msgstr ""

#: neutron/extensions/l3agentscheduler.py:162
#, python-format
msgid ""
"The router %(router_id)s has been already hosted by the L3 Agent "
"%(agent_id)s."
msgstr ""

#: neutron/extensions/l3agentscheduler.py:167
#, python-format
msgid "Failed scheduling router %(router_id)s to the L3 Agent %(agent_id)s."
msgstr ""

#: neutron/extensions/l3agentscheduler.py:172
#, python-format
msgid "Failed rescheduling router %(router_id)s: no eligible l3 agent found."
msgstr ""

#: neutron/extensions/l3agentscheduler.py:177
#, python-format
msgid "The router %(router_id)s is not hosted by L3 agent %(agent_id)s."
msgstr ""

#: neutron/extensions/l3agentscheduler.py:182
#, python-format
msgid ""
"Cannot host %(router_type)s router %(router_id)s on %(agent_mode)s L3 "
"agent %(agent_id)s."
msgstr ""

#: neutron/extensions/lbaas_agentscheduler.py:116
#, python-format
msgid "No eligible loadbalancer agent found for pool %(pool_id)s."
msgstr ""

#: neutron/extensions/lbaas_agentscheduler.py:121
#, python-format
msgid "No active loadbalancer agent found for pool %(pool_id)s."
msgstr ""

#: neutron/extensions/loadbalancer.py:33
#: neutron/extensions/loadbalancerv2.py:75
msgid "Delay must be greater than or equal to timeout"
msgstr ""

#: neutron/extensions/loadbalancer.py:37
#, python-format
msgid "No eligible backend for pool %(pool_id)s"
msgstr ""

#: neutron/extensions/loadbalancer.py:41
#, python-format
msgid "Vip %(vip_id)s could not be found"
msgstr ""

#: neutron/extensions/loadbalancer.py:45
#, python-format
msgid "Another Vip already exists for pool %(pool_id)s"
msgstr ""

#: neutron/extensions/loadbalancer.py:49
#, python-format
msgid "Pool %(pool_id)s could not be found"
msgstr ""

#: neutron/extensions/loadbalancer.py:53
#, python-format
msgid "Member %(member_id)s could not be found"
msgstr ""

#: neutron/extensions/loadbalancer.py:57
#, python-format
msgid "Health_monitor %(monitor_id)s could not be found"
msgstr ""

#: neutron/extensions/loadbalancer.py:61
#, python-format
msgid "Monitor %(monitor_id)s is not associated with Pool %(pool_id)s"
msgstr ""

#: neutron/extensions/loadbalancer.py:66
#, python-format
msgid "health_monitor %(monitor_id)s is already associated with pool %(pool_id)s"
msgstr ""

#: neutron/extensions/loadbalancer.py:71
#, python-format
msgid "Invalid state %(state)s of Loadbalancer resource %(id)s"
msgstr ""

#: neutron/extensions/loadbalancer.py:75
#, python-format
msgid "Pool %(pool_id)s is still in use"
msgstr ""

#: neutron/extensions/loadbalancer.py:79
#, python-format
msgid "Health monitor %(monitor_id)s still has associations with pools"
msgstr ""

#: neutron/extensions/loadbalancer.py:84
#, python-format
msgid "Statistics of Pool %(pool_id)s could not be found"
msgstr ""

#: neutron/extensions/loadbalancer.py:88
#, python-format
msgid "Protocol %(vip_proto)s does not match pool protocol %(pool_proto)s"
msgstr ""

#: neutron/extensions/loadbalancer.py:93
#, python-format
msgid ""
"Member with address %(address)s and port %(port)s already present in pool"
" %(pool)s"
msgstr ""

#: neutron/extensions/loadbalancer.py:311
msgid "Number of vips allowed per tenant. A negative value means unlimited."
msgstr ""

#: neutron/extensions/loadbalancer.py:315
#: neutron/extensions/loadbalancerv2.py:348
msgid "Number of pools allowed per tenant. A negative value means unlimited."
msgstr ""

#: neutron/extensions/loadbalancer.py:319
#: neutron/extensions/loadbalancerv2.py:352
msgid ""
"Number of pool members allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/extensions/loadbalancer.py:323
#: neutron/extensions/loadbalancerv2.py:356
msgid ""
"Number of health monitors allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/extensions/loadbalancerv2.py:67
#, python-format
msgid "Required attribute %(attr_name)s not specified"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:71
#, python-format
msgid "%(name)s %(id)s could not be found"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:79
#, python-format
msgid "%(entity_using)s %(id)s is using this %(entity_in_use)s"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:83
#, python-format
msgid ""
"Load Balancer %(lb_id)s already has a listener with protocol_port of "
"%(protocol_port)s"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:88
#, python-format
msgid ""
"Listener protocol %(listener_proto)s and pool protocol %(pool_proto)s are"
" not compatible."
msgstr ""

#: neutron/extensions/loadbalancerv2.py:93
#, python-format
msgid "Cannot change %(attribute)s if one already exists"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:97
#, python-format
msgid "Invalid state %(state)s of loadbalancer resource %(id)s"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:101
#, python-format
msgid "Member %(member_id)s could not be found in pool %(pool_id)s"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:105
#, python-format
msgid ""
"Member with address %(address)s and protocol_port %(port)s already "
"present in pool %(pool)s"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:110
#, python-format
msgid ""
"Member with address %(address)s and subnet %(subnet_id)  have mismatched "
"IP versions"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:115
msgid "An error happened in the driver"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:119
#, python-format
msgid ""
"Load balancer %(load_balancer_id)s configuration is notsupported by "
"driver %(driver_name)s"
msgstr ""

#: neutron/extensions/loadbalancerv2.py:340
msgid ""
"Number of LoadBalancers allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/extensions/loadbalancerv2.py:344
msgid ""
"Number of Loadbalancer Listeners allowed per tenant. A negative value "
"means unlimited."
msgstr ""

#: neutron/extensions/metering.py:31
#, python-format
msgid "Metering label %(label_id)s does not exist"
msgstr ""

#: neutron/extensions/metering.py:35
msgid "Duplicate Metering Rule in POST."
msgstr ""

#: neutron/extensions/metering.py:39
#, python-format
msgid "Metering label rule %(rule_id)s does not exist"
msgstr ""

#: neutron/extensions/metering.py:43
#, python-format
msgid ""
"Metering label rule with remote_ip_prefix %(remote_ip_prefix)s overlaps "
"another"
msgstr ""

#: neutron/extensions/multiprovidernet.py:27
msgid "Segments and provider values cannot both be set."
msgstr ""

#: neutron/extensions/multiprovidernet.py:31
msgid "Duplicate segment entry in request."
msgstr ""

#: neutron/extensions/portsecurity.py:20
msgid ""
"Port has security group associated. Cannot disable port security or ip "
"address until security group is removed"
msgstr ""

#: neutron/extensions/portsecurity.py:25
msgid ""
"Port security must be enabled and port must have an IP address in order "
"to use security groups."
msgstr ""

#: neutron/extensions/portsecurity.py:30
msgid "Port does not have port security binding."
msgstr ""

#: neutron/extensions/providernet.py:54
#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:270
msgid "Plugin does not support updating provider attributes"
msgstr ""

#: neutron/extensions/quotasv2.py:66
msgid "POST requests are not supported on this resource."
msgstr ""

#: neutron/extensions/quotasv2.py:85
msgid "Only admin is authorized to access quotas for another tenant"
msgstr ""

#: neutron/extensions/quotasv2.py:90
msgid "Only admin can view or configure quota"
msgstr ""

#: neutron/extensions/securitygroup.py:34
msgid "For TCP/UDP protocols, port_range_min must be <= port_range_max"
msgstr ""

#: neutron/extensions/securitygroup.py:39
#, python-format
msgid "Invalid value for port %(port)s"
msgstr ""

#: neutron/extensions/securitygroup.py:43
#, python-format
msgid ""
"Invalid value for ICMP %(field)s (%(attr)s) %(value)s. It must be 0 to "
"255."
msgstr ""

#: neutron/extensions/securitygroup.py:48
#, python-format
msgid ""
"ICMP code (port-range-max) %(value)s is provided but ICMP type (port-"
"range-min) is missing."
msgstr ""

#: neutron/extensions/securitygroup.py:53
#, python-format
msgid "Security Group %(id)s in use."
msgstr ""

#: neutron/extensions/securitygroup.py:57
msgid "Removing default security group not allowed."
msgstr ""

#: neutron/extensions/securitygroup.py:61
msgid "Updating default security group not allowed."
msgstr ""

#: neutron/extensions/securitygroup.py:65
msgid "Default security group already exists."
msgstr ""

#: neutron/extensions/securitygroup.py:69
#, python-format
msgid ""
"Security group rule protocol %(protocol)s not supported. Only protocol "
"values %(values)s and their integer representation (0 to 255) are "
"supported."
msgstr ""

#: neutron/extensions/securitygroup.py:75
msgid "Multiple tenant_ids in bulk security group rule create not allowed"
msgstr ""

#: neutron/extensions/securitygroup.py:80
msgid "Only remote_ip_prefix or remote_group_id may be provided."
msgstr ""

#: neutron/extensions/securitygroup.py:85
msgid "Must also specifiy protocol if port range is given."
msgstr ""

#: neutron/extensions/securitygroup.py:89
msgid "Only allowed to update rules for one security profile at a time"
msgstr ""

#: neutron/extensions/securitygroup.py:94
#, python-format
msgid "Security group %(id)s does not exist"
msgstr ""

#: neutron/extensions/securitygroup.py:98
#, python-format
msgid "Security group rule %(id)s does not exist"
msgstr ""

#: neutron/extensions/securitygroup.py:102
msgid "Duplicate Security Group Rule in POST."
msgstr ""

#: neutron/extensions/securitygroup.py:106
#, python-format
msgid "Security group rule already exists. Rule id is %(id)s."
msgstr ""

#: neutron/extensions/securitygroup.py:110
#, python-format
msgid "Conflicting value ethertype %(ethertype)s for CIDR %(cidr)s"
msgstr ""

#: neutron/extensions/securitygroup.py:161
#, python-format
msgid "'%s' is not an integer or uuid"
msgstr ""

#: neutron/extensions/securitygroup.py:250
msgid ""
"Number of security groups allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/extensions/securitygroup.py:254
msgid ""
"Number of security rules allowed per tenant. A negative value means "
"unlimited."
msgstr ""

#: neutron/extensions/servicetype.py:49
msgid "Neutron Service Type Management"
msgstr ""

#: neutron/extensions/servicetype.py:57
msgid "API for retrieving service providers for Neutron advanced services"
msgstr ""

#: neutron/extensions/vpnaas.py:29
#, python-format
msgid "VPNService %(vpnservice_id)s could not be found"
msgstr ""

#: neutron/extensions/vpnaas.py:33
#, python-format
msgid "ipsec_site_connection %(ipsec_site_conn_id)s not found"
msgstr ""

#: neutron/extensions/vpnaas.py:37
#, python-format
msgid "ipsec_site_connection %(attr)s is equal to or less than dpd_interval"
msgstr ""

#: neutron/extensions/vpnaas.py:42
#, python-format
msgid "ipsec_site_connection MTU %(mtu)d is too small for ipv%(version)s"
msgstr ""

#: neutron/extensions/vpnaas.py:47
#, python-format
msgid "IKEPolicy %(ikepolicy_id)s could not be found"
msgstr ""

#: neutron/extensions/vpnaas.py:51
#, python-format
msgid "IPsecPolicy %(ipsecpolicy_id)s could not be found"
msgstr ""

#: neutron/extensions/vpnaas.py:55
#, python-format
msgid ""
"IKEPolicy %(ikepolicy_id)s is in use by existing IPsecSiteConnection and "
"can't be updated or deleted"
msgstr ""

#: neutron/extensions/vpnaas.py:60
#, python-format
msgid "VPNService %(vpnservice_id)s is still in use"
msgstr ""

#: neutron/extensions/vpnaas.py:64
#, python-format
msgid "Router %(router_id)s is used by VPNService %(vpnservice_id)s"
msgstr ""

#: neutron/extensions/vpnaas.py:68
#, python-format
msgid "Subnet %(subnet_id)s is used by VPNService %(vpnservice_id)s"
msgstr ""

#: neutron/extensions/vpnaas.py:72
#, python-format
msgid "Invalid state %(state)s of vpnaas resource %(id)s for updating"
msgstr ""

#: neutron/extensions/vpnaas.py:77
#, python-format
msgid ""
"IPsecPolicy %(ipsecpolicy_id)s is in use by existing IPsecSiteConnection "
"and can't be updated or deleted"
msgstr ""

#: neutron/extensions/vpnaas.py:82
#, python-format
msgid "Can not load driver :%(device_driver)s"
msgstr ""

#: neutron/extensions/vpnaas.py:86
#, python-format
msgid "Subnet %(subnet_id)s is not connected to Router %(router_id)s"
msgstr ""

#: neutron/extensions/vpnaas.py:91
#, python-format
msgid "Router %(router_id)s has no external network gateway set"
msgstr ""

#: neutron/openstack/common/lockutils.py:101
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: neutron/openstack/common/log.py:298
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: neutron/openstack/common/log.py:406
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: neutron/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: neutron/openstack/common/log.py:715
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: neutron/openstack/common/periodic_task.py:46
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr ""

#: neutron/openstack/common/policy.py:97
msgid "The JSON file that defines policies."
msgstr ""

#: neutron/openstack/common/policy.py:100
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: neutron/openstack/common/policy.py:104
msgid "Directories where policy configuration files are stored."
msgstr ""

#: neutron/openstack/common/policy.py:119
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: neutron/openstack/common/policy.py:213
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: neutron/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: neutron/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: neutron/openstack/common/processutils.py:143
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: neutron/openstack/common/processutils.py:148
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: neutron/openstack/common/processutils.py:158
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: neutron/openstack/common/processutils.py:206
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: neutron/openstack/common/processutils.py:248
msgid "Environment not supported over SSH"
msgstr ""

#: neutron/openstack/common/processutils.py:252
msgid "process_input not supported over SSH"
msgstr ""

#: neutron/openstack/common/versionutils.py:90
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: neutron/openstack/common/versionutils.py:94
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: neutron/openstack/common/versionutils.py:98
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: neutron/openstack/common/versionutils.py:101
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: neutron/plugins/bigswitch/config.py:28
msgid ""
"A comma separated list of Big Switch or Floodlight servers and port "
"numbers. The plugin proxies the requests to the Big Switch/Floodlight "
"server, which performs the networking configuration. Only oneserver is "
"needed per deployment, but you may wish todeploy multiple servers to "
"support failover."
msgstr ""

#: neutron/plugins/bigswitch/config.py:35
msgid ""
"The username and password for authenticating against  the Big Switch or "
"Floodlight controller."
msgstr ""

#: neutron/plugins/bigswitch/config.py:38
msgid ""
"If True, Use SSL when connecting to the Big Switch or Floodlight "
"controller."
msgstr ""

#: neutron/plugins/bigswitch/config.py:41
msgid ""
"Trust and store the first certificate received for each controller "
"address and use it to validate future connections to that address."
msgstr ""

#: neutron/plugins/bigswitch/config.py:45
msgid "Disables SSL certificate validation for controllers"
msgstr ""

#: neutron/plugins/bigswitch/config.py:47
msgid "Re-use HTTP/HTTPS connections to the controller."
msgstr ""

#: neutron/plugins/bigswitch/config.py:50
msgid "Directory containing ca_certs and host_certs certificate directories."
msgstr ""

#: neutron/plugins/bigswitch/config.py:53
msgid "Sync data on connect"
msgstr ""

#: neutron/plugins/bigswitch/config.py:55
msgid ""
"If neutron fails to create a resource because the backend controller "
"doesn't know of a dependency, the plugin automatically triggers a full "
"data synchronization to the controller."
msgstr ""

#: neutron/plugins/bigswitch/config.py:60
msgid ""
"Time between verifications that the backend controller database is "
"consistent with Neutron. (0 to disable)"
msgstr ""

#: neutron/plugins/bigswitch/config.py:63
msgid ""
"Maximum number of seconds to wait for proxy request to connect and "
"complete."
msgstr ""

#: neutron/plugins/bigswitch/config.py:66
msgid ""
"Maximum number of threads to spawn to handle large volumes of port "
"creations."
msgstr ""

#: neutron/plugins/bigswitch/config.py:70
msgid "User defined identifier for this Neutron deployment"
msgstr ""

#: neutron/plugins/bigswitch/config.py:72
msgid ""
"Flag to decide if a route to the metadata server should be injected into "
"the VM"
msgstr ""

#: neutron/plugins/bigswitch/config.py:77
msgid ""
"The default router rules installed in new tenant routers. Repeat the "
"config option for each rule. Format is "
"<tenant>:<source>:<destination>:<action> Use an * to specify default for "
"all tenants."
msgstr ""

#: neutron/plugins/bigswitch/config.py:82
msgid "Maximum number of router rules"
msgstr ""

#: neutron/plugins/bigswitch/config.py:86
msgid "Virtual interface type to configure on Nova compute nodes"
msgstr ""

#: neutron/plugins/bigswitch/config.py:93
#, python-format
msgid "Nova compute nodes to manually set VIF type to %s"
msgstr ""

#: neutron/plugins/bigswitch/config.py:100
msgid "List of allowed vif_type values."
msgstr ""

#: neutron/plugins/bigswitch/config.py:104
msgid ""
"Name of integration bridge on compute nodes used for security group "
"insertion."
msgstr ""

#: neutron/plugins/bigswitch/config.py:107
msgid "Seconds between agent checks for port changes"
msgstr ""

#: neutron/plugins/bigswitch/config.py:109
msgid "Virtual switch type."
msgstr ""

#: neutron/plugins/bigswitch/l3_router_plugin.py:59
msgid "L3 Router Service Plugin for Big Switch fabric"
msgstr ""

#: neutron/plugins/bigswitch/plugin.py:93
msgid "Syntax error in server config file, aborting plugin"
msgstr ""

#: neutron/plugins/bigswitch/plugin.py:233
#, python-format
msgid "Unable to update remote topology: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:79
#, python-format
msgid "Error in REST call to remote network controller: %(reason)s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:269
msgid "Servers not defined. Aborting server manager."
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:276
#, python-format
msgid "Servers must be defined as <ip>:<port>. Configuration was %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:335
#, python-format
msgid "ssl_cert_directory [%s] does not exist. Create it or disable ssl."
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:352
#, python-format
msgid "No certificates were found to verify controller %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:395
#, python-format
msgid ""
"Could not retrieve initial certificate from controller %(server)s. Error "
"details: %(error)s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:454
msgid "Server requires synchronization, but no topology function was defined."
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:524
#, python-format
msgid "Unable to create remote router: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:530
#, python-format
msgid "Unable to update remote router: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:535
#, python-format
msgid "Unable to delete remote router: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:541
#, python-format
msgid "Unable to add router interface: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:546
#, python-format
msgid "Unable to delete remote intf: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:552
#, python-format
msgid "Unable to create remote network: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:558
#: neutron/plugins/bigswitch/servermanager.py:563
#, python-format
msgid "Unable to update remote network: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:578
#, python-format
msgid "Unable to create remote port: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:583
#, python-format
msgid "Unable to delete remote port: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:593
#, python-format
msgid "Unable to create floating IP: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:598
#, python-format
msgid "Unable to update floating IP: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:603
#, python-format
msgid "Unable to delete floating IP: %s"
msgstr ""

#: neutron/plugins/bigswitch/servermanager.py:608
#, python-format
msgid "Unable to retrieve switch: %s"
msgstr ""

#: neutron/plugins/bigswitch/extensions/routerrule.py:26
#, python-format
msgid "Invalid format for router rules: %(rule)s, %(reason)s"
msgstr ""

#: neutron/plugins/bigswitch/extensions/routerrule.py:30
#, python-format
msgid ""
"Unable to complete rules update for %(router_id)s. The number of rules "
"exceeds the maximum %(quota)s."
msgstr ""

#: neutron/plugins/bigswitch/extensions/routerrule.py:47
#, python-format
msgid "Invalid data format for router rule: '%s'"
msgstr ""

#: neutron/plugins/bigswitch/extensions/routerrule.py:79
#, python-format
msgid "Duplicate nexthop in rule '%s'"
msgstr ""

#: neutron/plugins/bigswitch/extensions/routerrule.py:87
#, python-format
msgid "Action must be either permit or deny. '%s' was provided"
msgstr ""

#: neutron/plugins/bigswitch/extensions/routerrule.py:99
#, python-format
msgid "Duplicate router rules (src,dst)  found '%s'"
msgstr ""

#: neutron/plugins/brocade/NeutronPlugin.py:62
#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:32
#: neutron/services/l3_router/brocade/l3_router_plugin.py:37
msgid "The address of the host to SSH to"
msgstr ""

#: neutron/plugins/brocade/NeutronPlugin.py:64
#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:34
#: neutron/services/l3_router/brocade/l3_router_plugin.py:39
msgid "The SSH username to use"
msgstr ""

#: neutron/plugins/brocade/NeutronPlugin.py:66
#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:36
#: neutron/services/l3_router/brocade/l3_router_plugin.py:41
msgid "The SSH password to use"
msgstr ""

#: neutron/plugins/brocade/NeutronPlugin.py:68
msgid "Currently unused"
msgstr ""

#: neutron/plugins/brocade/NeutronPlugin.py:72
msgid "The network interface to use when creatinga port"
msgstr ""

#: neutron/plugins/brocade/NeutronPlugin.py:300
#: neutron/plugins/brocade/NeutronPlugin.py:341
#: neutron/plugins/brocade/NeutronPlugin.py:394
#: neutron/plugins/brocade/NeutronPlugin.py:425
msgid "Brocade plugin raised exception, check logs"
msgstr ""

#: neutron/plugins/cisco/network_plugin.py:114
#, python-format
msgid "'%(model)s' object has no attribute '%(name)s'"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:101
msgid ""
"Interval when the process_services() loop executes in seconds. This is "
"when the config agent lets each service helper to process its neutron "
"resources."
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_agent.py:108
msgid "Path of the routing service helper class."
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_exceptions.py:26
msgid ""
"Critical device parameter missing. Failed initializing CSR1kv routing "
"driver."
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_exceptions.py:32
#, python-format
msgid ""
"Failed connecting to CSR1kv. Reason: %(reason)s. Connection params are "
"User:%(user)s, Host:%(host)s, Port:%(port)s, Device timeout:%(timeout)s."
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_exceptions.py:39
#, python-format
msgid "Error executing snippet:%(snippet)s. ErrorType:%(type)s ErrorTag:%(tag)s."
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_exceptions.py:45
#, python-format
msgid ""
"Data in attribute: %(attribute)s does not correspond to expected value. "
"Value received is %(value)s. "
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_exceptions.py:50
#, python-format
msgid "Driver %(driver)s does not exist."
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_exceptions.py:54
#, python-format
msgid "Driver not found for resource id:%(id)s."
msgstr ""

#: neutron/plugins/cisco/cfg_agent/cfg_exceptions.py:58
#, python-format
msgid "Driver cannot be set for missing parameter:%(p)s."
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_status.py:30
msgid "Time in seconds for connecting to a hosting device"
msgstr ""

#: neutron/plugins/cisco/cfg_agent/device_status.py:32
msgid ""
"The time in seconds until a backlogged hosting device is presumed dead. "
"This value should be set up high enough to recover from a period of "
"connectivity loss or high load when the device may not be responding."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:22
#, python-format
msgid "Segmentation ID for network %(net_id)s is not found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:27
msgid ""
"Unable to complete operation. No more dynamic NICs are available in the "
"system."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:33
#, python-format
msgid ""
"NetworkVlanBinding for %(vlan_id)s and network %(network_id)s already "
"exists."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:39
#, python-format
msgid "Vlan ID %(vlan_id)s not found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:44
msgid ""
"Unable to complete operation. VLAN ID exists outside of the configured "
"network segment range."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:50
msgid "No Vlan ID available."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:55
#, python-format
msgid "QoS level %(qos_id)s could not be found for tenant %(tenant_id)s."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:61
#, python-format
msgid "QoS level with name %(qos_name)s already exists for tenant %(tenant_id)s."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:67
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:23
#, python-format
msgid "Credential %(credential_id)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:72
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:28
#, python-format
msgid "Credential %(credential_name)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:77
#, python-format
msgid "Credential %(credential_name)s already exists."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:82
#, python-format
msgid "Provider network %s already exists"
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:87
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:39
#, python-format
msgid "Connection to %(host)s is not configured."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:92
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:44
#, python-format
msgid "Unable to connect to Nexus %(nexus_host)s. Reason: %(exc)s."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:97
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:49
#, python-format
msgid "Failed to configure Nexus: %(config)s. Reason: %(exc)s."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:102
#, python-format
msgid "Nexus Port Binding (%(filters)s) is not present."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:111
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:69
msgid "No usable Nexus switch found to create SVI interface."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:116
#, python-format
msgid "PortVnic Binding %(port_id)s already exists."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:121
#, python-format
msgid "PortVnic Binding %(port_id)s is not present."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:126
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:74
msgid "No subnet_id specified for router gateway."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:131
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:79
#, python-format
msgid "Subnet %(subnet_id)s has an interface on %(router_id)s."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:136
#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:84
msgid "Nexus hardware router gateway only uses Subnet Ids."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:140
#, python-format
msgid ""
"Unable to unplug the attachment %(att_id)s from port %(port_id)s for "
"network %(net_id)s. The attachment %(att_id)s does not exist."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:147
#, python-format
msgid "Policy Profile %(profile_id)s already exists."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:153
#, python-format
msgid "Policy Profile %(profile_id)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:158
#, python-format
msgid "Policy Profile %(profile_name)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:163
#, python-format
msgid "Network Profile %(profile_id)s already exists."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:169
#, python-format
msgid "Network Profile %(profile)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:174
#, python-format
msgid ""
"One or more network segments belonging to network profile %(profile)s is "
"in use."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:180
#, python-format
msgid ""
"No more segments available in network segment pool "
"%(network_profile_name)s."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:186
#, python-format
msgid "VM Network %(name)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:191
#, python-format
msgid "Unable to create the network. The VXLAN ID %(vxlan_id)s is in use."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:197
#, python-format
msgid "Vxlan ID %(vxlan_id)s not found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:202
msgid ""
"Unable to complete operation. VXLAN ID exists outside of the configured "
"network segment range."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:208
#, python-format
msgid "Connection to VSM failed: %(reason)s."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:213
#, python-format
msgid "Internal VSM Error: %(reason)s."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:218
#, python-format
msgid "Network Binding for network %(network_id)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:224
#, python-format
msgid "Port Binding for port %(port_id)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:230
#, python-format
msgid "Profile-Tenant binding for profile %(profile_id)s could not be found."
msgstr ""

#: neutron/plugins/cisco/common/cisco_exceptions.py:236
msgid "No service cluster found to perform multi-segment bridging."
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:70
msgid "Port not Found"
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:71
msgid "Unable to find a port with the specified identifier."
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:85
msgid "Credential Not Found"
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:86
msgid "Unable to find a Credential with the specified identifier."
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:101
msgid "QoS Not Found"
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:102
msgid "Unable to find a QoS with the specified identifier."
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:117
msgid "Nova tenant Not Found"
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:118
msgid "Unable to find a Novatenant with the specified identifier."
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:133
msgid "Requested State Invalid"
msgstr ""

#: neutron/plugins/cisco/common/cisco_faults.py:134
msgid "Unable to update port state with specified value."
msgstr ""

#: neutron/plugins/cisco/common/config.py:22
#: neutron/plugins/ml2/drivers/cisco/nexus/config.py:21
msgid "VLAN Name prefix"
msgstr ""

#: neutron/plugins/cisco/common/config.py:24
msgid "VLAN Name prefix for provider vlans"
msgstr ""

#: neutron/plugins/cisco/common/config.py:26
msgid "Provider VLANs are automatically created as needed on the Nexus switch"
msgstr ""

#: neutron/plugins/cisco/common/config.py:29
msgid ""
"Provider VLANs are automatically trunked as needed on the ports of the "
"Nexus switch"
msgstr ""

#: neutron/plugins/cisco/common/config.py:32
msgid "Enable L3 support on the Nexus switches"
msgstr ""

#: neutron/plugins/cisco/common/config.py:34
#: neutron/plugins/ml2/drivers/cisco/nexus/config.py:23
msgid "Distribute SVI interfaces over all switches"
msgstr ""

#: neutron/plugins/cisco/common/config.py:38
msgid "Model Class"
msgstr ""

#: neutron/plugins/cisco/common/config.py:43
msgid "N1K Integration Bridge"
msgstr ""

#: neutron/plugins/cisco/common/config.py:45
msgid "N1K Enable Tunneling"
msgstr ""

#: neutron/plugins/cisco/common/config.py:47
msgid "N1K Tunnel Bridge"
msgstr ""

#: neutron/plugins/cisco/common/config.py:49
msgid "N1K Local IP"
msgstr ""

#: neutron/plugins/cisco/common/config.py:51
msgid "N1K Tenant Network Type"
msgstr ""

#: neutron/plugins/cisco/common/config.py:53
msgid "N1K Bridge Mappings"
msgstr ""

#: neutron/plugins/cisco/common/config.py:55
msgid "N1K VXLAN ID Ranges"
msgstr ""

#: neutron/plugins/cisco/common/config.py:57
msgid "N1K Network VLAN Ranges"
msgstr ""

#: neutron/plugins/cisco/common/config.py:59
msgid "N1K default network profile"
msgstr ""

#: neutron/plugins/cisco/common/config.py:61
msgid "N1K default policy profile"
msgstr ""

#: neutron/plugins/cisco/common/config.py:63
msgid "N1K policy profile for network node"
msgstr ""

#: neutron/plugins/cisco/common/config.py:65
msgid "N1K Policy profile polling duration in seconds"
msgstr ""

#: neutron/plugins/cisco/common/config.py:67
msgid "Restrict the visibility of policy profiles to the tenants"
msgstr ""

#: neutron/plugins/cisco/common/config.py:70
msgid "Number of threads to use to make HTTP requests"
msgstr ""

#: neutron/plugins/cisco/common/config.py:72
msgid "N1K http timeout duration in seconds"
msgstr ""

#: neutron/plugins/cisco/common/config.py:74
msgid ""
"Restrict tenants from accessing network profiles belonging to some other "
"tenant"
msgstr ""

#: neutron/plugins/cisco/common/config.py:127
#: neutron/plugins/ml2/drivers/cisco/nexus/config.py:58
msgid "Some config files were not parsed properly"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:596
#, python-format
msgid "Unreasonable vxlan ID range %(vxlan_min)s - %(vxlan_max)s"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:892
#: neutron/plugins/cisco/db/n1kv_db_v2.py:946
msgid "Invalid profile type"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1136
msgid "segment_range not required for TRUNK"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1142
msgid "multicast_ip_range not required"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1271
msgid "Invalid segment range. example range: 500-550"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1284
msgid "Invalid multicast ip address range. example range: 224.1.1.1-224.1.1.10"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1291
#, python-format
msgid "%s is not a valid multicast ip address"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1295
#, python-format
msgid "%s is reserved multicast ip address"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1299
#, python-format
msgid "%s is not a valid ip address"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1303
#, python-format
msgid ""
"Invalid multicast IP range '%(min_ip)s-%(max_ip)s': Range should be from "
"low address to high address"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1316
msgid "Arguments segment_type missing for network profile"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1325
msgid "segment_type should either be vlan, overlay, multi-segment or trunk"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1331
msgid "Argument physical_network missing for network profile"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1337
msgid "segment_range not required for trunk"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1343
msgid "Argument sub_type missing for network profile"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1350
msgid "Argument segment_range missing for network profile"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1361
msgid "Argument multicast_ip_range missing for VXLAN multicast network profile"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1389
#, python-format
msgid "Segment range is invalid, select from %(min)s-%(nmin)s, %(nmax)s-%(max)s"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1407
#, python-format
msgid "segment range is invalid. Valid range is : %(min)s-%(max)s"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1421
#, python-format
msgid "NetworkProfile name %s already exists"
msgstr ""

#: neutron/plugins/cisco/db/n1kv_db_v2.py:1438
msgid "Segment range overlaps with another profile"
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:43
msgid "Name of the L3 admin tenant."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:45
msgid ""
"Name of management network for device configuration. Default value is "
"osn_mgmt_nw"
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:48
msgid ""
"Default security group applied on management port. Default value is "
"mgmt_sec_grp."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:51
msgid "Seconds of no status update until a cfg agent is considered down."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:54
msgid "Ensure that Nova is running before attempting to create any VM."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:60
msgid "Name of Glance image for CSR1kv."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:62
msgid "UUID of Nova flavor for CSR1kv."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:66
msgid "Plugging driver for CSR1kv."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:70
msgid "Hosting device driver for CSR1kv."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:74
msgid "Config agent driver for CSR1kv."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:76
msgid "Booting time in seconds before a CSR1kv becomes operational."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:79
msgid "Username to use for CSR1kv configurations."
msgstr ""

#: neutron/plugins/cisco/db/l3/device_handling_db.py:81
msgid "Password to use for CSR1kv configurations."
msgstr ""

#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:47
msgid ""
"Time in seconds between renewed scheduling attempts of non-scheduled "
"routers."
msgstr ""

#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:55
msgid "Router could not be created due to internal error."
msgstr ""

#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:59
msgid "Internal error during router processing."
msgstr ""

#: neutron/plugins/cisco/db/l3/l3_router_appliance_db.py:63
#, python-format
msgid "Could not get binding information for router %(router_id)s."
msgstr ""

#: neutron/plugins/cisco/l3/service_vm_lib.py:31
msgid "Path to templates for hosting devices."
msgstr ""

#: neutron/plugins/cisco/l3/service_vm_lib.py:34
msgid "Path to config drive files for service VM instances."
msgstr ""

#: neutron/plugins/cisco/l3/hosting_device_drivers/csr1kv_hd_driver.py:33
msgid "CSR1kv configdrive template file."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:41
msgid "Name of N1kv port profile for management ports."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:43
msgid ""
"Name of N1kv port profile for T1 ports (i.e., ports carrying traffic from"
" VXLAN segmented networks)."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:46
msgid ""
"Name of N1kv port profile for T2 ports (i.e., ports carrying traffic from"
" VLAN segmented networks)."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:49
msgid ""
"Name of N1kv network profile for T1 networks (i.e., trunk networks for "
"VXLAN segmented traffic)."
msgstr ""

#: neutron/plugins/cisco/l3/plugging_drivers/n1kv_trunking_driver.py:52
msgid ""
"Name of N1kv network profile for T2 networks (i.e., trunk networks for "
"VLAN segmented traffic)."
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_client.py:296
msgid "Invalid input for CIDR"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:210
#: neutron/plugins/mlnx/mlnx_plugin.py:227 neutron/plugins/nuage/plugin.py:419
msgid "provider:network_type required"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:214
#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:228
#: neutron/plugins/nuage/plugin.py:429
msgid "provider:segmentation_id required"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:217
msgid "provider:segmentation_id out of range (1 through 4094)"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:222
msgid "provider:physical_network specified for Overlay network"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:231
msgid "provider:segmentation_id out of range (5000+)"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:235
#, python-format
msgid "provider:network_type %s not supported"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:246
#, python-format
msgid "Unknown provider:physical_network %s"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:250
#: neutron/plugins/nuage/plugin.py:426
msgid "provider:physical_network required"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:467
msgid "Invalid pairing supplied"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:473
msgid "Invalid UUID supplied"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:502
#, python-format
msgid "Cannot add a trunk segment '%s' as a member of another trunk segment"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:507
#, python-format
msgid "Cannot add vlan segment '%s' as a member of a vxlan trunk segment"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:513
#, python-format
msgid "Network UUID '%s' belongs to a different physical network"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:518
#, python-format
msgid "Cannot add vxlan segment '%s' as a member of a vlan trunk segment"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:523
#, python-format
msgid "Vlan tag '%s' is out of range"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:526
#, python-format
msgid "Vlan tag '%s' is not an integer value"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:578
#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:581
msgid "n1kv:profile_id does not exist"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:1022
#, python-format
msgid "Cannot delete network '%s', delete the associated subnet first"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:1026
#, python-format
msgid "Cannot delete network '%s' that is member of a trunk segment"
msgstr ""

#: neutron/plugins/cisco/n1kv/n1kv_neutron_plugin.py:1030
#, python-format
msgid "Cannot delete network '%s' that is a member of a multi-segment network"
msgstr ""

#: neutron/plugins/common/utils.py:33
#, python-format
msgid "%(id)s is not a valid %(type)s identifier"
msgstr ""

#: neutron/plugins/common/utils.py:38
msgid "End of tunnel range is less than start of tunnel range"
msgstr ""

#: neutron/plugins/common/utils.py:48
#, python-format
msgid "%s is not a valid VLAN tag"
msgstr ""

#: neutron/plugins/common/utils.py:52
msgid "End of VLAN range is less than start of VLAN range"
msgstr ""

#: neutron/plugins/embrane/common/config.py:21
msgid "ESM management root address"
msgstr ""

#: neutron/plugins/embrane/common/config.py:23
msgid "ESM admin username."
msgstr ""

#: neutron/plugins/embrane/common/config.py:26
msgid "ESM admin password."
msgstr ""

#: neutron/plugins/embrane/common/config.py:28
msgid "Router image id (Embrane FW/VPN)"
msgstr ""

#: neutron/plugins/embrane/common/config.py:30
msgid "In band Security Zone id"
msgstr ""

#: neutron/plugins/embrane/common/config.py:32
msgid "Out of band Security Zone id"
msgstr ""

#: neutron/plugins/embrane/common/config.py:34
msgid "Management Security Zone id"
msgstr ""

#: neutron/plugins/embrane/common/config.py:36
msgid "Dummy user traffic Security Zone id"
msgstr ""

#: neutron/plugins/embrane/common/config.py:38
msgid "Shared resource pool id"
msgstr ""

#: neutron/plugins/embrane/common/config.py:40
msgid "Define if the requests have run asynchronously or not"
msgstr ""

#: neutron/plugins/embrane/common/constants.py:47
#, python-format
msgid "Dva is pending for the following reason: %s"
msgstr ""

#: neutron/plugins/embrane/common/constants.py:48
msgid ""
"Dva can't be found to execute the operation, probably was cancelled "
"through the heleos UI"
msgstr ""

#: neutron/plugins/embrane/common/constants.py:50
#, python-format
msgid "Dva seems to be broken for reason %s"
msgstr ""

#: neutron/plugins/embrane/common/constants.py:51
#, python-format
msgid "Dva interface seems to be broken for reason %s"
msgstr ""

#: neutron/plugins/embrane/common/constants.py:53
#, python-format
msgid "Dva creation failed reason %s"
msgstr ""

#: neutron/plugins/embrane/common/constants.py:54
#, python-format
msgid "Dva creation is in pending state for reason %s"
msgstr ""

#: neutron/plugins/embrane/common/constants.py:56
#, python-format
msgid "Dva configuration failed for reason %s"
msgstr ""

#: neutron/plugins/embrane/common/constants.py:57
#, python-format
msgid ""
"Failed to delete the backend router for reason %s. Please remove it "
"manually through the heleos UI"
msgstr ""

#: neutron/plugins/embrane/common/exceptions.py:20
#, python-format
msgid "An unexpected error occurred:%(err_msg)s"
msgstr ""

#: neutron/plugins/embrane/common/exceptions.py:24
#, python-format
msgid "%(err_msg)s"
msgstr ""

#: neutron/plugins/embrane/l2base/support_exceptions.py:20
#, python-format
msgid "Cannot retrieve utif info for the following reason: %(err_msg)s"
msgstr ""

#: neutron/plugins/embrane/l2base/ml2/ml2_support.py:43
#, python-format
msgid ""
"Network type %s not supported. Please be sure that tenant_network_type is"
" vlan"
msgstr ""

#: neutron/plugins/hyperv/hyperv_neutron_plugin.py:47
msgid "Network type for tenant networks (local, flat, vlan or none)"
msgstr ""

#: neutron/plugins/hyperv/hyperv_neutron_plugin.py:51
#: neutron/plugins/linuxbridge/common/config.py:30
#: neutron/plugins/mlnx/common/config.py:30
msgid "List of <physical_network>:<vlan_min>:<vlan_max> or <physical_network>"
msgstr ""

#: neutron/plugins/hyperv/hyperv_neutron_plugin.py:79
#: neutron/plugins/hyperv/hyperv_neutron_plugin.py:101
#, python-format
msgid "segmentation_id specified for %s network"
msgstr ""

#: neutron/plugins/hyperv/hyperv_neutron_plugin.py:86
#, python-format
msgid "physical_network specified for %s network"
msgstr ""

#: neutron/plugins/hyperv/hyperv_neutron_plugin.py:128
msgid "physical_network not provided"
msgstr ""

#: neutron/plugins/hyperv/hyperv_neutron_plugin.py:180
#, python-format
msgid "Invalid tenant_network_type: %s. Agent terminated!"
msgstr ""

#: neutron/plugins/hyperv/hyperv_neutron_plugin.py:231
#, python-format
msgid "Network type %s not supported"
msgstr ""

#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:49
msgid ""
"List of <physical_network>:<vswitch> where the physical networks can be "
"expressed with wildcards, e.g.: .\"*:external\""
msgstr ""

#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:55
msgid "Private vswitch name used for local networks"
msgstr ""

#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:57
#: neutron/plugins/linuxbridge/common/config.py:61
#: neutron/plugins/mlnx/common/config.py:67
#: neutron/plugins/nec/common/config.py:28
#: neutron/plugins/oneconvergence/lib/config.py:47
#: neutron/plugins/openvswitch/common/config.py:53
#: neutron/plugins/sriovnicagent/common/config.py:58
msgid ""
"The number of seconds the agent will wait between polling for local "
"device changes."
msgstr ""

#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:61
msgid ""
"Enables metrics collections for switch ports by using Hyper-V's metric "
"APIs. Collected data can by retrieved by other apps and services, e.g.: "
"Ceilometer. Requires Hyper-V / Windows Server 2012 and above"
msgstr ""

#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:68
msgid ""
"Specifies the maximum number of retries to enable Hyper-V's port metrics "
"collection. The agent will try to enable the feature once every "
"polling_interval period for at most metrics_max_retries or until it "
"succeedes."
msgstr ""

#: neutron/plugins/hyperv/agent/hyperv_neutron_agent.py:253
#, python-format
msgid ""
"Cannot provision unknown network type %(network_type)s for network "
"%(net_uuid)s"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:34
#, python-format
msgid "HyperVException: %(msg)s"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:79
#, python-format
msgid "Vnic not found: %s"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:114
#, python-format
msgid "Job failed with error %d"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:133
#, python-format
msgid ""
"WMI job failed with status %(job_state)d. Error details: %(err_sum_desc)s"
" - %(err_desc)s - Error code: %(err_code)d"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:142
#, python-format
msgid "WMI job failed with status %(job_state)d. Error details: %(error)s"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:146
#, python-format
msgid "WMI job failed with status %d. No error description available"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:165
#, python-format
msgid "Failed creating port for %s"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:188
#, python-format
msgid ""
"Failed to disconnect port %(switch_port_name)s from switch "
"%(vswitch_name)s with error %(ret_val)s"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:199
#, python-format
msgid ""
"Failed to delete port %(switch_port_name)s from switch %(vswitch_name)s "
"with error %(ret_val)s"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:206
#: neutron/plugins/hyperv/agent/utilsv2.py:133
#, python-format
msgid "VSwitch not found: %s"
msgstr ""

#: neutron/plugins/hyperv/agent/utils.py:247
#: neutron/plugins/hyperv/agent/utils.py:251
msgid "Metrics collection is not supported on this version of Hyper-V"
msgstr ""

#: neutron/plugins/hyperv/agent/utilsfactory.py:32
msgid "Force V1 WMI utility classes"
msgstr ""

#: neutron/plugins/hyperv/agent/utilsv2.py:156
#: neutron/plugins/hyperv/agent/utilsv2.py:316
#, python-format
msgid "Port Allocation not found: %s"
msgstr ""

#: neutron/plugins/hyperv/agent/utilsv2.py:266
#, python-format
msgid "Cannot get VM summary data for: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_api.py:96
#, python-format
msgid "unable to serialize object type: '%s'"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:161
#, python-format
msgid "Original SDN-VE HTTP request: %(orig)s; New request: %(new)s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:180
msgid "Create net failed: no SDN-VE tenant."
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:191
#, python-format
msgid "Create net failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:218
#, python-format
msgid "Update net failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:298
#, python-format
msgid "Create port failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:332
#, python-format
msgid "Update port failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:372
#, python-format
msgid "Create subnet failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:405
#, python-format
msgid "Update subnet failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:438
msgid "Create router failed: no SDN-VE tenant."
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:446
#, python-format
msgid "Create router failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:460
msgid "admin_state_up=False routers are not supported."
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:484
#, python-format
msgid "Update router failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:524
#, python-format
msgid "Update router-add-interface failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:556
msgid "No port ID"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:562
msgid "No fixed IP"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:590
#, python-format
msgid "Update router-remove-interface failed SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:622
#, python-format
msgid "Creating floating ip operation failed in SDN-VE controller: %s"
msgstr ""

#: neutron/plugins/ibm/sdnve_neutron_plugin.py:650
#, python-format
msgid "Update floating ip failed in SDN-VE: %s"
msgstr ""

#: neutron/plugins/ibm/common/config.py:26
msgid "Whether to use a fake controller."
msgstr ""

#: neutron/plugins/ibm/common/config.py:28
msgid "Base URL for SDN-VE controller REST API."
msgstr ""

#: neutron/plugins/ibm/common/config.py:30
msgid "List of IP addresses of SDN-VE controller(s)."
msgstr ""

#: neutron/plugins/ibm/common/config.py:32
msgid "SDN-VE RPC subject."
msgstr ""

#: neutron/plugins/ibm/common/config.py:34
msgid "SDN-VE controller port number."
msgstr ""

#: neutron/plugins/ibm/common/config.py:36
msgid "SDN-VE request/response format."
msgstr ""

#: neutron/plugins/ibm/common/config.py:38
msgid "SDN-VE administrator user ID."
msgstr ""

#: neutron/plugins/ibm/common/config.py:40
msgid "SDN-VE administrator password."
msgstr ""

#: neutron/plugins/ibm/common/config.py:42
#: neutron/plugins/nec/common/config.py:23
#: neutron/plugins/openvswitch/common/config.py:29
msgid "Integration bridge to use."
msgstr ""

#: neutron/plugins/ibm/common/config.py:44
msgid "Whether to reset the integration bridge before use."
msgstr ""

#: neutron/plugins/ibm/common/config.py:46
msgid "Indicating if controller is out of band or not."
msgstr ""

#: neutron/plugins/ibm/common/config.py:49
msgid "List of <physical_network_name>:<interface_name> mappings."
msgstr ""

#: neutron/plugins/ibm/common/config.py:52
msgid "Tenant type: OVERLAY (default) or OF."
msgstr ""

#: neutron/plugins/ibm/common/config.py:54
msgid ""
"The string in tenant description that indicates the tenant is a OVERLAY "
"tenant."
msgstr ""

#: neutron/plugins/ibm/common/config.py:57
msgid "The string in tenant description that indicates the tenant is a OF tenant."
msgstr ""

#: neutron/plugins/ibm/common/config.py:63
msgid "Agent polling interval if necessary."
msgstr ""

#: neutron/plugins/ibm/common/config.py:65
msgid "Using root helper."
msgstr ""

#: neutron/plugins/ibm/common/config.py:67
msgid "Whether to use rpc."
msgstr ""

#: neutron/plugins/ibm/common/exceptions.py:21
#, python-format
msgid ""
"An unexpected error occurred in the SDN-VE Plugin. Here is the error "
"message: %(msg)s"
msgstr ""

#: neutron/plugins/ibm/common/exceptions.py:26
#, python-format
msgid "The input does not contain nececessary info: %(msg)s"
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:26
#: neutron/plugins/mlnx/common/config.py:26
msgid "Network type for tenant networks (local, vlan, or none)"
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:36
msgid ""
"Enable VXLAN on the agent. Can be enabled when agent is managed by ml2 "
"plugin using linuxbridge mechanism driver"
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:40
msgid "TTL for vxlan interface protocol packets."
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:42
msgid "TOS for vxlan interface protocol packets."
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:44
msgid "Multicast group for vxlan interface."
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:46
msgid "Local IP address of the VXLAN endpoints."
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:48
msgid ""
"Extension to use alongside ml2 plugin's l2population mechanism driver. It"
" enables the plugin to populate VXLAN forwarding table."
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:56
#: neutron/plugins/mlnx/common/config.py:45
#: neutron/plugins/ofagent/common/config.py:29
msgid "List of <physical_network>:<physical_interface>"
msgstr ""

#: neutron/plugins/linuxbridge/common/config.py:64
#: neutron/plugins/mlnx/common/config.py:70
msgid "Enable server RPC compatibility with old agents"
msgstr ""

#: neutron/plugins/metaplugin/meta_neutron_plugin.py:60
#, python-format
msgid "Flavor %(flavor)s could not be found"
msgstr ""

#: neutron/plugins/metaplugin/meta_neutron_plugin.py:64
msgid "Failed to add flavor binding"
msgstr ""

#: neutron/plugins/metaplugin/meta_neutron_plugin.py:122
#, python-format
msgid "default_flavor %s is not plugin list"
msgstr ""

#: neutron/plugins/metaplugin/meta_neutron_plugin.py:128
#, python-format
msgid "default_l3_flavor %s is not plugin list"
msgstr ""

#: neutron/plugins/metaplugin/meta_neutron_plugin.py:134
#, python-format
msgid "rpc_flavor %s is not plugin list"
msgstr ""

#: neutron/plugins/metaplugin/common/config.py:23
msgid ""
"Comma separated list of flavor:neutron_plugin for plugins to load. "
"Extension method is searched in the list order and the first one is used."
msgstr ""

#: neutron/plugins/metaplugin/common/config.py:29
msgid ""
"Comma separated list of flavor:neutron_plugin for L3 service plugins to "
"load. This is intended for specifying L2 plugins which support L3 "
"functions. If you use a router service plugin, set this blank."
msgstr ""

#: neutron/plugins/metaplugin/common/config.py:36
msgid ""
"Default flavor to use, when flavor:network is not specified at network "
"creation."
msgstr ""

#: neutron/plugins/metaplugin/common/config.py:41
msgid ""
"Default L3 flavor to use, when flavor:router is not specified at router "
"creation. Ignored if 'l3_plugin_list' is blank."
msgstr ""

#: neutron/plugins/metaplugin/common/config.py:47
msgid "Comma separated list of supported extension aliases."
msgstr ""

#: neutron/plugins/metaplugin/common/config.py:51
msgid ""
"Comma separated list of method:flavor to select specific plugin for a "
"method. This has priority over method search order based on "
"'plugin_list'."
msgstr ""

#: neutron/plugins/metaplugin/common/config.py:57
msgid "Specifies flavor for plugin to handle 'q-plugin' RPC requests."
msgstr ""

#: neutron/plugins/midonet/midonet_lib.py:40
#, python-format
msgid "MidoNet %(resource_type)s %(id)s could not be found"
msgstr ""

#: neutron/plugins/midonet/midonet_lib.py:44
#: neutron/plugins/midonet/plugin.py:82
#, python-format
msgid "MidoNet API error: %(msg)s"
msgstr ""

#: neutron/plugins/midonet/midonet_lib.py:155
msgid "Tried to add tonon-existent DHCP"
msgstr ""

#: neutron/plugins/midonet/midonet_lib.py:214
msgid "Tried to delete non-existent DHCP"
msgstr ""

#: neutron/plugins/midonet/midonet_lib.py:356
msgid "Tried to access non-existent DHCP"
msgstr ""

#: neutron/plugins/midonet/midonet_lib.py:523
#, python-format
msgid "Invalid NAT type passed in %s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:96
#, python-format
msgid "Invalid nat_type %s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:153
#, python-format
msgid "Unrecognized direction %s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:194
#: neutron/plugins/ml2/drivers/arista/exceptions.py:23
#: neutron/plugins/ml2/drivers/arista/exceptions.py:27
#: neutron/plugins/ml2/drivers/arista/exceptions.py:31
#: neutron/plugins/ml2/drivers/arista/exceptions.py:35
#, python-format
msgid "%(msg)s"
msgstr ""

#: neutron/plugins/midonet/plugin.py:231
msgid "provider_router_id should be configured in the plugin config file"
msgstr ""

#: neutron/plugins/midonet/common/config.py:21
msgid "MidoNet API server URI."
msgstr ""

#: neutron/plugins/midonet/common/config.py:23
msgid "MidoNet admin username."
msgstr ""

#: neutron/plugins/midonet/common/config.py:26
msgid "MidoNet admin password."
msgstr ""

#: neutron/plugins/midonet/common/config.py:29
msgid "ID of the project that MidoNet admin userbelongs to."
msgstr ""

#: neutron/plugins/midonet/common/config.py:32
msgid "Virtual provider router ID."
msgstr ""

#: neutron/plugins/midonet/common/config.py:35
msgid "Operational mode. Internal dev use only."
msgstr ""

#: neutron/plugins/midonet/common/config.py:38
msgid "Path to midonet host uuid file"
msgstr ""

#: neutron/plugins/ml2/config.py:22
msgid ""
"List of network type driver entrypoints to be loaded from the "
"neutron.ml2.type_drivers namespace."
msgstr ""

#: neutron/plugins/ml2/config.py:26
msgid "Ordered list of network_types to allocate as tenant networks."
msgstr ""

#: neutron/plugins/ml2/config.py:30
msgid ""
"An ordered list of networking mechanism driver entrypoints to be loaded "
"from the neutron.ml2.mechanism_drivers namespace."
msgstr ""

#: neutron/plugins/ml2/config.py:35
msgid ""
"An ordered list of extension driver entrypoints to be loaded from the "
"neutron.ml2.extension_drivers namespace."
msgstr ""

#: neutron/plugins/ml2/managers.py:88
msgid "network_type required"
msgstr ""

#: neutron/plugins/ml2/managers.py:170 neutron/plugins/ml2/managers.py:179
#: neutron/plugins/ml2/drivers/type_tunnel.py:178
#, python-format
msgid "network_type value '%s' not supported"
msgstr ""

#: neutron/plugins/ml2/plugin.py:210
msgid "binding:profile value too large"
msgstr ""

#: neutron/plugins/ml2/common/exceptions.py:23
#, python-format
msgid "%(method)s failed."
msgstr ""

#: neutron/plugins/ml2/drivers/mechanism_ncs.py:29
msgid "HTTP URL of Tail-f NCS REST interface."
msgstr ""

#: neutron/plugins/ml2/drivers/mechanism_ncs.py:31
#: neutron/plugins/ml2/drivers/mechanism_odl.py:41
msgid "HTTP username for authentication"
msgstr ""

#: neutron/plugins/ml2/drivers/mechanism_ncs.py:33
#: neutron/plugins/ml2/drivers/mechanism_odl.py:43
msgid "HTTP password for authentication"
msgstr ""

#: neutron/plugins/ml2/drivers/mechanism_ncs.py:35
#: neutron/plugins/ml2/drivers/mechanism_odl.py:45
msgid "HTTP timeout in seconds."
msgstr ""

#: neutron/plugins/ml2/drivers/mechanism_odl.py:39
msgid "HTTP URL of OpenDaylight REST interface."
msgstr ""

#: neutron/plugins/ml2/drivers/mechanism_odl.py:47
msgid "Tomcat session timeout in minutes."
msgstr ""

#: neutron/plugins/ml2/drivers/type_flat.py:32
msgid ""
"List of physical_network names with which flat networks can be created. "
"Use * to allow flat networks with arbitrary physical_network names."
msgstr ""

#: neutron/plugins/ml2/drivers/type_flat.py:73
msgid "physical network name is empty"
msgstr ""

#: neutron/plugins/ml2/drivers/type_flat.py:91
msgid "physical_network required for flat provider network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_flat.py:94
#, python-format
msgid "physical_network '%s' unknown for flat provider network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_flat.py:101
#, python-format
msgid "%s prohibited for flat provider network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_gre.py:35
msgid ""
"Comma-separated list of <tun_min>:<tun_max> tuples enumerating ranges of "
"GRE tunnel IDs that are available for tenant network allocation"
msgstr ""

#: neutron/plugins/ml2/drivers/type_local.py:50
#, python-format
msgid "%s prohibited for local provider network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_tunnel.py:87
#, python-format
msgid "provider:physical_network specified for %s network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_tunnel.py:94
#, python-format
msgid "%(key)s prohibited for %(tunnel)s provider network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_tunnel.py:165
msgid "Network_type value needed by the ML2 plugin"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:39
msgid ""
"List of <physical_network>:<vlan_min>:<vlan_max> or <physical_network> "
"specifying physical_network names usable for VLAN provider and tenant "
"networks, as well as ranges of VLAN tags on each available for allocation"
" to tenant networks."
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:172
#, python-format
msgid "physical_network '%s' unknown  for VLAN provider network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:177
#, python-format
msgid "segmentation_id out of range (%(min)s through %(max)s)"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:183
msgid "segmentation_id requires physical_network for VLAN provider network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vlan.py:191
#, python-format
msgid "%s prohibited for VLAN provider network"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vxlan.py:38
msgid ""
"Comma-separated list of <vni_min>:<vni_max> tuples enumerating ranges of "
"VXLAN VNI IDs that are available for tenant network allocation"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vxlan.py:42
msgid "Multicast group for VXLAN. If unset, disables VXLAN multicast mode."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:30
#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:33
msgid "Unable to reach EOS"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:132
msgid "Required option primary_l3_host is not set"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:138
msgid "VRFs are not supported MLAG config mode"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:142
msgid "Required option secondary_l3_host is not set"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:146
msgid "Required option primary_l3_host_username is not set"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:262
#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:281
#, python-format
msgid "Failed to create router %s on EOS"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:323
#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:355
#, python-format
msgid "Failed to add interface to router %s on EOS"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/arista_l3_driver.py:382
#, python-format
msgid "Error occured while trying to execute commands %(cmd)s on EOS %(host)s"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:31
msgid ""
"Username for Arista EOS. This is required field. If not set, all "
"communications to Arista EOSwill fail."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:37
msgid ""
"Password for Arista EOS. This is required field. If not set, all "
"communications to Arista EOS will fail."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:42
msgid ""
"Arista EOS IP address. This is required field. If not set, all "
"communications to Arista EOSwill fail."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:47
msgid ""
"Defines if hostnames are sent to Arista EOS as FQDNs "
"(\"node1.domain.com\") or as short names (\"node1\"). This is optional. "
"If not set, a value of \"True\" is assumed."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:53
msgid ""
"Sync interval in seconds between Neutron plugin and EOS. This interval "
"defines how often the synchronization is performed. This is an optional "
"field. If not set, a value of 180 seconds is assumed."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:60
msgid ""
"Defines Region Name that is assigned to this OpenStack Controller. This "
"is useful when multiple OpenStack/Neutron controllers are managing the "
"same Arista HW clusters. Note that this name must match with the region "
"name registered (or known) to keystone service. Authentication with "
"Keysotne is performed by EOS. This is optional. If not set, a value of "
"\"RegionOne\" is assumed."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:81
msgid ""
"Username for Arista EOS. This is required field. If not set, all "
"communications to Arista EOS will fail"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:87
msgid ""
"Password for Arista EOS. This is required field. If not set, all "
"communications to Arista EOS will fail"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:92
msgid ""
"Arista EOS IP address. This is required field. If not set, all "
"communications to Arista EOS will fail"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:97
msgid ""
"Arista EOS IP address for second Switch MLAGed with the first one. This "
"an optional field, however, if mlag_config flag is set, then this is "
"required. If not set, all communications to Arista EOS will fail"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:104
msgid ""
"This flag is used indicate if Arista Switches are configured in MLAG "
"mode. If yes, all L3 config is pushed to both the switches automatically."
" If this flag is set to True, ensure to specify IP addresses of both "
"switches. This is optional. If not set, a value of \"False\" is assumed."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:113
msgid ""
"A \"True\" value for this flag indicates to create a router in VRF. If "
"not set, all routers are created in default VRF.This is optional. If not "
"set, a value of \"False\" is assumed."
msgstr ""

#: neutron/plugins/ml2/drivers/arista/config.py:120
msgid ""
"Sync interval in seconds between L3 Service plugin and EOS. This interval"
" defines how often the synchronization is performed. This is an optional "
"field. If not set, a value of 180 seconds is assumed"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:466
#, python-format
msgid "Error %(err)s while trying to execute commands %(cmd)s on EOS %(host)s"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:538
msgid "Required option eapi_host is not set"
msgstr ""

#: neutron/plugins/ml2/drivers/arista/mechanism_arista.py:542
msgid "Required option eapi_username is not set"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:38
msgid "Allowed physical networks"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:40
msgid "OS Type of the switch"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:42
msgid "OS Version number"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:133
msgid ""
"Brocade Mechanism: failed to create network, network cannot be created in"
" the configured physical network"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:139
msgid ""
"Brocade Mechanism: failed to create network, only network type vlan is "
"supported"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:149
msgid "Brocade Mechanism: create_network_precommit failed"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:186
msgid "Brocade Mechanism: create_network_postcommmit failed"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:215
msgid "Brocade Mechanism: delete_network_precommit failed"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:243
msgid "Brocade switch exception, delete_network_postcommit failed"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:285
msgid "Brocade Mechanism: create_port_precommit failed"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:317
msgid "Brocade switch exception: create_port_postcommit failed"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:340
msgid "Brocade Mechanism: delete_port_precommit failed"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/mechanism_brocade.py:372
msgid "Brocade switch exception, delete_port_postcommit failed"
msgstr ""

#: neutron/plugins/ml2/drivers/brocade/nos/nosdriver.py:74
msgid ""
"Brocade Switch IP address is not set, check config ml2_conf_brocade.ini "
"file"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:28
msgid "Prefix for APIC domain/names/profiles created"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:38
msgid "An ordered list of host names or IP addresses of the APIC controller(s)."
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:41
msgid "Username for the APIC controller"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:43
msgid "Password for the APIC controller"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:46
msgid "Name mapping strategy to use: use_uuid | use_name"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:48
msgid "Use SSL to connect to the APIC controller"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:51
msgid "Name for the domain created on APIC"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:54
msgid "Name for the app profile used for Openstack"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:57
msgid "Name for the vlan namespace to be used for Openstack"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:60
msgid "Name of the node profile to be created"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:63
msgid "Name of the entity profile to be created"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:66
msgid "Name of the function profile to be created"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:69
msgid "Name of the LACP profile to be created"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:72
msgid "The uplink ports to check for ACI connectivity"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:75
msgid "The switch pairs for VPC connectivity"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:78
msgid "Range of VLAN's to be used for Openstack"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:81
msgid "Setup root helper as rootwrap or sudo"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:84
msgid "Synchronization interval in seconds"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:87
msgid "Interval between agent status updates (in sec)"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/config.py:90
msgid "Interval between agent poll for topology (in sec)"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/nexus/config.py:25
msgid "The physical network managed by the switches."
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:33
#, python-format
msgid "Credential %(credential_name)s already exists for tenant %(tenant_id)s."
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:54
#, python-format
msgid "Nexus Port Binding (%(filters)s) is not present"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/nexus/exceptions.py:63
#, python-format
msgid "Missing required field(s) to configure nexus switch: %(fields)s"
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:28
msgid "CRD service Username."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:31
msgid "CRD Service Password."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:33
msgid "CRD Tenant Name."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:36
msgid "CRD Auth URL."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:39
msgid "URL for connecting to CRD service."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:42
msgid "Timeout value for connecting to CRD service in seconds."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:46
msgid "Region name for connecting to CRD Service in admin context."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:50
msgid "If set, ignore any SSL validation issues."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:53
msgid "Auth strategy for connecting to neutron in admin context."
msgstr ""

#: neutron/plugins/ml2/drivers/freescale/config.py:56
msgid "Location of ca certificates file to use for CRD client requests."
msgstr ""

#: neutron/plugins/ml2/drivers/l2pop/config.py:21
msgid ""
"Delay within which agent is expected to update existing ports whent it "
"restarts"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_bigswitch/driver.py:207
#, python-format
msgid "No cache entry for host %s"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_bigswitch/driver.py:212
#, python-format
msgid "Expired cache entry for host %s"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:32
msgid ""
"Supported PCI vendor devices, defined by vendor_id:product_id according "
"to the PCI ID Repository. Default enables support for Intel and Mellanox "
"SR-IOV capable NICs"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:38
msgid "SRIOV neutron agent is required for port binding"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:88
msgid "Parsing supported pci_vendor_devs failed"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:177
#, python-format
msgid "Invalid pci_vendor_info: '%s'"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:180
#, python-format
msgid "Missing vendor_id in: '%s'"
msgstr ""

#: neutron/plugins/ml2/drivers/mech_sriov/mech_driver.py:183
#, python-format
msgid "Missing product_id in: '%s'"
msgstr ""

#: neutron/plugins/ml2/drivers/mlnx/config.py:24
#: neutron/plugins/mlnx/common/config.py:48
msgid "Type of VM network interface: mlnx_direct or hostdev"
msgstr ""

#: neutron/plugins/mlnx/common/config.py:34
msgid ""
"List of <physical_network>:<physical_network_type>  with "
"physical_network_type is either eth or ib"
msgstr ""

#: neutron/plugins/mlnx/common/config.py:37
msgid "Physical network type for provider network (eth or ib)"
msgstr ""

#: neutron/plugins/mlnx/common/config.py:52
msgid "eswitch daemon end point"
msgstr ""

#: neutron/plugins/mlnx/common/config.py:54
msgid ""
"The number of milliseconds the agent will wait for response on request to"
" daemon."
msgstr ""

#: neutron/plugins/mlnx/common/config.py:57
msgid ""
"The number of retries the agent will send request to daemon before giving"
" up"
msgstr ""

#: neutron/plugins/mlnx/common/config.py:60
msgid ""
"backoff rate multiplier for waiting period between retries for request to"
" daemon, i.e. value of 2 will  double the request timeout each retry"
msgstr ""

#: neutron/plugins/mlnx/common/exceptions.py:20
#, python-format
msgid "Mlnx Exception: %(err_msg)s"
msgstr ""

#: neutron/plugins/mlnx/common/exceptions.py:24
msgid "Request Timeout: no response from eSwitchD"
msgstr ""

#: neutron/plugins/mlnx/common/exceptions.py:28
#, python-format
msgid "Operation Failed: %(err_msg)s"
msgstr ""

#: neutron/plugins/nec/packet_filter.py:249
#, python-format
msgid "Error occurred while disabling packet filter(s) for port %s"
msgstr ""

#: neutron/plugins/nec/common/config.py:34
msgid "Host to connect to."
msgstr ""

#: neutron/plugins/nec/common/config.py:36
msgid "Base URL of OFC REST API. It is prepended to each API request."
msgstr ""

#: neutron/plugins/nec/common/config.py:39
msgid "Port to connect to."
msgstr ""

#: neutron/plugins/nec/common/config.py:41
msgid "Driver to use."
msgstr ""

#: neutron/plugins/nec/common/config.py:43
msgid "Enable packet filter."
msgstr ""

#: neutron/plugins/nec/common/config.py:45
msgid "Support packet filter on OFC router interface."
msgstr ""

#: neutron/plugins/nec/common/config.py:47
msgid "Use SSL to connect."
msgstr ""

#: neutron/plugins/nec/common/config.py:49
msgid "Location of key file."
msgstr ""

#: neutron/plugins/nec/common/config.py:51
msgid "Location of certificate file."
msgstr ""

#: neutron/plugins/nec/common/config.py:53
msgid "Disable SSL certificate verification."
msgstr ""

#: neutron/plugins/nec/common/config.py:55
msgid ""
"Maximum attempts per OFC API request. NEC plugin retries API request to "
"OFC when OFC returns ServiceUnavailable (503). The value must be greater "
"than 0."
msgstr ""

#: neutron/plugins/nec/common/config.py:64
msgid "Default router provider to use."
msgstr ""

#: neutron/plugins/nec/common/config.py:67
msgid "List of enabled router providers."
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:19
#, python-format
msgid "An OFC exception has occurred: %(reason)s"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:29
#, python-format
msgid "The specified OFC resource (%(resource)s) is not found."
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:33
#, python-format
msgid "An exception occurred in NECPluginV2 DB: %(reason)s"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:37
#, python-format
msgid ""
"Neutron-OFC resource mapping for %(resource)s %(neutron_id)s is not "
"found. It may be deleted during processing."
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:43
#, python-format
msgid "OFC returns Server Unavailable (503) (Retry-After=%(retry_after)s)"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:52
#, python-format
msgid "PortInfo %(id)s could not be found"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:56
msgid ""
"Invalid input for operation: datapath_id should be a hex string with at "
"most 8 bytes"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:62
msgid "Invalid input for operation: port_no should be [0:65535]"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:67
#, python-format
msgid "Router (provider=%(provider)s) does not support an external network"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:72
#, python-format
msgid "Provider %(provider)s could not be found"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:76
#, python-format
msgid "Cannot create more routers with provider=%(provider)s"
msgstr ""

#: neutron/plugins/nec/common/exceptions.py:80
#, python-format
msgid ""
"Provider of Router %(router_id)s is %(provider)s. This operation is "
"supported only for router provider %(expected_provider)s."
msgstr ""

#: neutron/plugins/nec/common/ofc_client.py:54
#, python-format
msgid "Operation on OFC failed: %(status)s%(msg)s"
msgstr ""

#: neutron/plugins/nec/common/ofc_client.py:115
msgid "Operation on OFC failed"
msgstr ""

#: neutron/plugins/nec/common/ofc_client.py:124
#, python-format
msgid "Failed to connect OFC : %s"
msgstr ""

#: neutron/plugins/nec/drivers/pfc.py:33
#, python-format
msgid "OFC %(resource)s ID has an invalid format: %(ofc_id)s"
msgstr ""

#: neutron/plugins/nec/extensions/packetfilter.py:30
msgid "Number of packet_filters allowed per tenant, -1 for unlimited"
msgstr ""

#: neutron/plugins/nec/extensions/packetfilter.py:37
#, python-format
msgid "PacketFilter %(id)s could not be found"
msgstr ""

#: neutron/plugins/nec/extensions/packetfilter.py:41
#, python-format
msgid ""
"IP version %(version)s is not supported for %(field)s (%(value)s is "
"specified)"
msgstr ""

#: neutron/plugins/nec/extensions/packetfilter.py:46
#, python-format
msgid "Packet Filter priority should be %(min)s-%(max)s (included)"
msgstr ""

#: neutron/plugins/nec/extensions/packetfilter.py:50
#, python-format
msgid "%(field)s field cannot be updated"
msgstr ""

#: neutron/plugins/nec/extensions/packetfilter.py:54
#, python-format
msgid ""
"The backend does not support duplicated priority. Priority %(priority)s "
"is in use"
msgstr ""

#: neutron/plugins/nec/extensions/packetfilter.py:59
#, python-format
msgid ""
"Ether Type '%(eth_type)s' conflicts with protocol '%(protocol)s'. Update "
"or clear protocol before changing ether type."
msgstr ""

#: neutron/plugins/nuage/plugin.py:113
#, python-format
msgid "%(resource)s with id %(resource_id)s does not exist"
msgstr ""

#: neutron/plugins/nuage/plugin.py:122
#, python-format
msgid ""
"Either %(resource)s %(req_resource)s not found or you dont have "
"credential to access it"
msgstr ""

#: neutron/plugins/nuage/plugin.py:128
#, python-format
msgid ""
"More than one entry found for %(resource)s %(req_resource)s. Use id "
"instead"
msgstr ""

#: neutron/plugins/nuage/plugin.py:158
#, python-format
msgid "Router for subnet %s not found "
msgstr ""

#: neutron/plugins/nuage/plugin.py:275
#, python-format
msgid "Subnet %s not found on VSD"
msgstr ""

#: neutron/plugins/nuage/plugin.py:422
#, python-format
msgid "provider:network_type %s not supported in VSP"
msgstr ""

#: neutron/plugins/nuage/plugin.py:469
msgid "External network with subnets can not be changed to non-external network"
msgstr ""

#: neutron/plugins/nuage/plugin.py:530
msgid ""
"Either net_partition is not provided with subnet OR default net_partition"
" is not created at the start"
msgstr ""

#: neutron/plugins/nuage/plugin.py:547
#, python-format
msgid "Only one subnet is allowed per Provider network %s"
msgstr ""

#: neutron/plugins/nuage/plugin.py:558
#, python-format
msgid "Only one subnet is allowed per external network %s"
msgstr ""

#: neutron/plugins/nuage/plugin.py:694
#, python-format
msgid ""
"Unable to complete operation on subnet %s.One or more ports have an IP "
"allocation from this subnet."
msgstr ""

#: neutron/plugins/nuage/plugin.py:721
#, python-format
msgid ""
"Router %s does not hold default zone OR domain in VSD. Router-IF add "
"failed"
msgstr ""

#: neutron/plugins/nuage/plugin.py:733
#, python-format
msgid "Subnet %s does not hold Nuage VSD reference. Router-IF add failed"
msgstr ""

#: neutron/plugins/nuage/plugin.py:743
#, python-format
msgid ""
"Subnet %(subnet)s and Router %(router)s belong to different net_partition"
" Router-IF add not permitted"
msgstr ""

#: neutron/plugins/nuage/plugin.py:754
#, python-format
msgid "Subnet %s has one or more active VMs Router-IF add not permitted"
msgstr ""

#: neutron/plugins/nuage/plugin.py:806 neutron/plugins/nuage/plugin.py:811
#: neutron/plugins/nuage/plugin.py:817
#, python-format
msgid "No router interface found for Router %s. Router-IF delete failed"
msgstr ""

#: neutron/plugins/nuage/plugin.py:833
#, python-format
msgid "Subnet %s has one or more active VMs Router-IF delete not permitted"
msgstr ""

#: neutron/plugins/nuage/plugin.py:842
#, python-format
msgid ""
"Router %s does not hold net_partition assoc on Nuage VSD. Router-IF "
"delete failed"
msgstr ""

#: neutron/plugins/nuage/plugin.py:883
msgid ""
"Either net_partition is not provided with router OR default net_partition"
" is not created at the start"
msgstr ""

#: neutron/plugins/nuage/plugin.py:924
msgid "for same subnet, multiple static routes not allowed"
msgstr ""

#: neutron/plugins/nuage/plugin.py:941
#, python-format
msgid "Router %s does not hold net-partition assoc on VSD. extra-route failed"
msgstr ""

#: neutron/plugins/nuage/plugin.py:1057
#, python-format
msgid "One or more router still attached to net_partition %s."
msgstr ""

#: neutron/plugins/nuage/plugin.py:1062
#, python-format
msgid "NetPartition with %s does not exist"
msgstr ""

#: neutron/plugins/nuage/plugin.py:1104
#, python-format
msgid "sharedresource %s not found on VSD"
msgstr ""

#: neutron/plugins/nuage/plugin.py:1111 neutron/plugins/nuage/plugin.py:1261
#, python-format
msgid "router %s is not associated with any net-partition"
msgstr ""

#: neutron/plugins/nuage/plugin.py:1144
msgid "Floating IP can not be associated to VM in different router context"
msgstr ""

#: neutron/plugins/nuage/common/config.py:20
msgid "IP Address and Port of Nuage's VSD server"
msgstr ""

#: neutron/plugins/nuage/common/config.py:23
msgid "Username and password for authentication"
msgstr ""

#: neutron/plugins/nuage/common/config.py:25
msgid "Boolean for SSL connection with VSD server"
msgstr ""

#: neutron/plugins/nuage/common/config.py:27
msgid "Nuage provided base uri to reach out to VSD"
msgstr ""

#: neutron/plugins/nuage/common/config.py:29
msgid ""
"Organization name in which VSD will orchestrate network resources using "
"openstack"
msgstr ""

#: neutron/plugins/nuage/common/config.py:32
msgid "Nuage provided uri for initial authorization to access VSD"
msgstr ""

#: neutron/plugins/nuage/common/config.py:36
msgid ""
"Default Network partition in which VSD will orchestrate network resources"
" using openstack"
msgstr ""

#: neutron/plugins/nuage/common/config.py:40
msgid "Per Net Partition quota of floating ips"
msgstr ""

#: neutron/plugins/nuage/common/config.py:45
msgid "Nuage plugin will sync resources between openstack and VSD"
msgstr ""

#: neutron/plugins/nuage/common/config.py:48
msgid ""
"Sync interval in seconds between openstack and VSD. It defines how often "
"the synchronization is done. If not set, value of 0 is assumed and sync "
"will be performed only once, at the Neutron startup time."
msgstr ""

#: neutron/plugins/nuage/common/exceptions.py:21
#, python-format
msgid "Nuage Plugin does not support this operation: %(msg)s"
msgstr ""

#: neutron/plugins/nuage/common/exceptions.py:25
#, python-format
msgid "Bad request: %(msg)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:914
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1508
#, python-format
msgid "Parsing bridge_mappings failed: %s."
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:919
#, python-format
msgid "Parsing physical_interface_mappings failed: %s."
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:939
#, python-format
msgid "Invalid tunnel type specificed: %s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:942
#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1536
msgid "Tunneling cannot be enabled without a valid local_ip."
msgstr ""

#: neutron/plugins/ofagent/common/config.py:25
msgid "Number of seconds to retry acquiring an Open vSwitch datapath"
msgstr ""

#: neutron/plugins/oneconvergence/lib/config.py:26
msgid "NVSD Controller IP address"
msgstr ""

#: neutron/plugins/oneconvergence/lib/config.py:29
msgid "NVSD Controller Port number"
msgstr ""

#: neutron/plugins/oneconvergence/lib/config.py:32
msgid "NVSD Controller username"
msgstr ""

#: neutron/plugins/oneconvergence/lib/config.py:35
msgid "NVSD Controller password"
msgstr ""

#: neutron/plugins/oneconvergence/lib/config.py:38
msgid "NVSD controller REST API request timeout in seconds"
msgstr ""

#: neutron/plugins/oneconvergence/lib/config.py:40
msgid "Number of login retries to NVSD controller"
msgstr ""

#: neutron/plugins/oneconvergence/lib/config.py:45
msgid "integration bridge"
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:23
#, python-format
msgid "An unknown nvsd plugin exception occurred: %(reason)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:27
#: neutron/plugins/vmware/api_client/exception.py:68
msgid "The request has timed out."
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:31
msgid "Invalid access credentials to the Server."
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:35
#, python-format
msgid "A resource is not found: %(reason)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:39
#, python-format
msgid "Request sent to server is invalid: %(reason)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:43
#, python-format
msgid "Internal Server Error: %(reason)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:47
msgid "Connection is closed by the server."
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:51
#, python-format
msgid "The request is forbidden access to the resource: %(reason)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/exception.py:55
#, python-format
msgid "Internal Server Error from NVSD controller: %(reason)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/nvsdlib.py:54
#, python-format
msgid "Could not create a %(resource)s under tenant %(tenant_id)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/nvsdlib.py:58
#, python-format
msgid "Failed to %(method)s %(resource)s id=%(resource_id)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/nvsdlib.py:64
#, python-format
msgid "Failed to %(method)s %(resource)s"
msgstr ""

#: neutron/plugins/oneconvergence/lib/plugin_helper.py:80
#, python-format
msgid "Unable to connect to NVSD controller. Exiting after %(retries)s attempts"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:60
#, python-format
msgid ""
"Unable to retrieve port details for devices: %(devices)s because of "
"error: %(error)s"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_neutron_agent.py:1533
#, python-format
msgid "Invalid tunnel type specified: %s"
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:31
msgid "Enable tunneling support."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:33
msgid "Tunnel bridge to use."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:35
msgid "Peer patch port in integration bridge for tunnel bridge."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:38
msgid "Peer patch port in tunnel bridge for integration bridge."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:41
msgid "Local IP address of tunnel endpoint."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:44
msgid "List of <physical_network>:<bridge>. Deprecated for ofagent."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:47
msgid ""
"Use veths instead of patch ports to interconnect the integration bridge "
"to physical bridges."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:57
msgid "Minimize polling by monitoring ovsdb for interface changes."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:61
msgid ""
"The number of seconds to wait before respawning the ovsdb monitor after "
"losing communication with it."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:64
msgid "Network types supported by the agent (gre and/or vxlan)."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:69
msgid "MTU size of veth interfaces"
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:71
msgid ""
"Use ML2 l2population mechanism driver to learn remote MAC and IPs and "
"improve tunnel scalability."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:74
msgid ""
"Enable local ARP responder if it is supported. Requires OVS 2.1 and ML2 "
"l2population driver. Allows the switch (when supporting an overlay) to "
"respond to an ARP request locally without performing a costly ARP "
"broadcast into the overlay."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:80
msgid ""
"Set or un-set the don't fragment (DF) bit on outgoing IP packet carrying "
"GRE/VXLAN tunnel."
msgstr ""

#: neutron/plugins/openvswitch/common/config.py:83
msgid "Make the l2 agent run in DVR mode."
msgstr ""

#: neutron/plugins/plumgrid/common/exceptions.py:22
#, python-format
msgid "PLUMgrid Plugin Error: %(err_msg)s"
msgstr ""

#: neutron/plugins/plumgrid/common/exceptions.py:26
#, python-format
msgid "Connection failed with PLUMgrid Director: %(err_msg)s"
msgstr ""

#: neutron/plugins/plumgrid/plumgrid_plugin/plumgrid_plugin.py:45
msgid "PLUMgrid Director server to connect to"
msgstr ""

#: neutron/plugins/plumgrid/plumgrid_plugin/plumgrid_plugin.py:47
msgid "PLUMgrid Director server port to connect to"
msgstr ""

#: neutron/plugins/plumgrid/plumgrid_plugin/plumgrid_plugin.py:49
msgid "PLUMgrid Director admin username"
msgstr ""

#: neutron/plugins/plumgrid/plumgrid_plugin/plumgrid_plugin.py:51
msgid "PLUMgrid Director admin password"
msgstr ""

#: neutron/plugins/plumgrid/plumgrid_plugin/plumgrid_plugin.py:53
msgid "PLUMgrid Director server timeout"
msgstr ""

#: neutron/plugins/plumgrid/plumgrid_plugin/plumgrid_plugin.py:56
msgid "PLUMgrid Driver"
msgstr ""

#: neutron/plugins/sriovnicagent/eswitch_manager.py:49
msgid "Device not found"
msgstr ""

#: neutron/plugins/sriovnicagent/eswitch_manager.py:63
msgid "Device has no virtual functions"
msgstr ""

#: neutron/plugins/sriovnicagent/sriov_nic_agent.py:318
#, python-format
msgid "Device name %(dev_name)s is missing from physical_device_mappings"
msgstr ""

#: neutron/plugins/sriovnicagent/common/config.py:41
#, python-format
msgid "Device %(dev_name)s in mapping: %(mapping)s not unique"
msgstr ""

#: neutron/plugins/sriovnicagent/common/config.py:65
msgid ""
"List of <physical_network>:<network_device> mapping physical network "
"names to the agent's node-specific physical network device of SR-IOV "
"physical function to be used for VLAN networks. All physical networks "
"listed in network_vlan_ranges on the server should have mappings to "
"appropriate interfaces on each agent"
msgstr ""

#: neutron/plugins/sriovnicagent/common/config.py:74
msgid ""
"List of <network_device>:<excluded_devices> mapping network_device to the"
" agent's node-specific list of virtual functions that should not be used "
"for virtual networking. excluded_devices is a semicolon separated list of"
" virtual functions (BDF format).to exclude from network_device. The "
"network_device in the mapping should appear in the "
"physical_device_mappings list."
msgstr ""

#: neutron/plugins/sriovnicagent/common/exceptions.py:24
#, python-format
msgid "Invalid Device %(dev_name)s: %(reason)s"
msgstr ""

#: neutron/plugins/sriovnicagent/common/exceptions.py:28
#, python-format
msgid "ip command failed on device %(dev_name)s: %(reason)s"
msgstr ""

#: neutron/plugins/sriovnicagent/common/exceptions.py:32
#, python-format
msgid "Invalid pci slot %(pci_slot)s"
msgstr ""

#: neutron/plugins/vmware/check_nsx_config.py:45
#: neutron/plugins/vmware/check_nsx_config.py:80
#, python-format
msgid "Error '%(err)s' when connecting to controller(s): %(ctl)s."
msgstr ""

#: neutron/plugins/vmware/dhcpmeta_modes.py:58
#, python-format
msgid "Invalid agent_mode: %s"
msgstr ""

#: neutron/plugins/vmware/dhcpmeta_modes.py:131
#, python-format
msgid "Unable to run Neutron with config option '%s', as NSX does not support it"
msgstr ""

#: neutron/plugins/vmware/dhcpmeta_modes.py:134
#, python-format
msgid "Unmet dependency for config option '%s'"
msgstr ""

#: neutron/plugins/vmware/nsx_cluster.py:50
#, python-format
msgid ""
"Attribute '%s' has been deprecated or moved to a new section. See new "
"configuration file for details."
msgstr ""

#: neutron/plugins/vmware/api_client/__init__.py:28
#, python-format
msgid "Invalid connection type: %s"
msgstr ""

#: neutron/plugins/vmware/api_client/eventlet_request.py:103
msgid "Joining an invalid green thread"
msgstr ""

#: neutron/plugins/vmware/api_client/eventlet_request.py:124
msgid "Request timeout"
msgstr ""

#: neutron/plugins/vmware/api_client/exception.py:41
msgid "Server denied session's authentication credentials."
msgstr ""

#: neutron/plugins/vmware/api_client/exception.py:45
msgid "An entity referenced in the request was not found."
msgstr ""

#: neutron/plugins/vmware/api_client/exception.py:49
msgid "Request conflicts with configuration on a different entity."
msgstr ""

#: neutron/plugins/vmware/api_client/exception.py:54
msgid ""
"Request could not completed because the associated resource could not be "
"reached."
msgstr ""

#: neutron/plugins/vmware/api_client/exception.py:59
msgid "The request is forbidden from accessing the referenced resource."
msgstr ""

#: neutron/plugins/vmware/api_client/exception.py:64
msgid "Create/Update actions are forbidden when in read-only mode."
msgstr ""

#: neutron/plugins/vmware/api_client/exception.py:72
msgid "The server is unable to fulfill the request due to a bad syntax"
msgstr ""

#: neutron/plugins/vmware/api_client/exception.py:77
msgid "The backend received an invalid security certificate."
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:85
msgid "No API connections available"
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:195
#, python-format
msgid "Server error return: %s"
msgstr ""

#: neutron/plugins/vmware/api_client/request.py:199
msgid "Invalid server response"
msgstr ""

#: neutron/plugins/vmware/common/config.py:39
msgid ""
"Maximum number of ports of a logical switch on a bridged transport zone "
"(default 5000)"
msgstr ""

#: neutron/plugins/vmware/common/config.py:43
msgid ""
"Maximum number of ports of a logical switch on an overlay transport zone "
"(default 256)"
msgstr ""

#: neutron/plugins/vmware/common/config.py:47
msgid "Maximum concurrent connections to each NSX controller."
msgstr ""

#: neutron/plugins/vmware/common/config.py:52
msgid ""
"Number of seconds a generation id should be valid for (default -1 meaning"
" do not time out)"
msgstr ""

#: neutron/plugins/vmware/common/config.py:56
msgid ""
"If set to access_network this enables a dedicated connection to the "
"metadata proxy for metadata server access via Neutron router. If set to "
"dhcp_host_route this enables host route injection via the dhcp agent. "
"This option is only useful if running on a host that does not support "
"namespaces otherwise access_network should be used."
msgstr ""

#: neutron/plugins/vmware/common/config.py:65
msgid ""
"The default network tranport type to use (stt, gre, bridge, ipsec_gre, or"
" ipsec_stt)"
msgstr ""

#: neutron/plugins/vmware/common/config.py:69
msgid "The mode used to implement DHCP/metadata services."
msgstr ""

#: neutron/plugins/vmware/common/config.py:71
msgid ""
"The default option leverages service nodes to perform packet replication "
"though one could set to this to 'source' to perform replication locally. "
"This is useful if one does not want to deploy a service node(s). It must "
"be set to 'service' for leveraging distributed routers."
msgstr ""

#: neutron/plugins/vmware/common/config.py:82
msgid ""
"Interval in seconds between runs of the state synchronization task. Set "
"it to 0 to disable it"
msgstr ""

#: neutron/plugins/vmware/common/config.py:86
msgid ""
"Maximum value for the additional random delay in seconds between runs of "
"the state synchronization task"
msgstr ""

#: neutron/plugins/vmware/common/config.py:91
msgid ""
"Minimum delay, in seconds, between two state synchronization queries to "
"NSX. It must not exceed state_sync_interval"
msgstr ""

#: neutron/plugins/vmware/common/config.py:96
msgid ""
"Minimum number of resources to be retrieved from NSX during state "
"synchronization"
msgstr ""

#: neutron/plugins/vmware/common/config.py:100
msgid ""
"Always read operational status from backend on show operations. Enabling "
"this option might slow down the system."
msgstr ""

#: neutron/plugins/vmware/common/config.py:109
msgid "User name for NSX controllers in this cluster"
msgstr ""

#: neutron/plugins/vmware/common/config.py:114
msgid "Password for NSX controllers in this cluster"
msgstr ""

#: neutron/plugins/vmware/common/config.py:117
msgid "Time before aborting a request"
msgstr ""

#: neutron/plugins/vmware/common/config.py:120
msgid "Number of time a request should be retried"
msgstr ""

#: neutron/plugins/vmware/common/config.py:123
msgid "Number of times a redirect should be followed"
msgstr ""

#: neutron/plugins/vmware/common/config.py:126
msgid "Lists the NSX controllers in this cluster"
msgstr ""

#: neutron/plugins/vmware/common/config.py:129
msgid "Reconnect connection to nsx if not used within this amount of time."
msgstr ""

#: neutron/plugins/vmware/common/config.py:135
msgid ""
"This is uuid of the default NSX Transport zone that will be used for "
"creating tunneled isolated \"Neutron\" networks. It needs to be created "
"in NSX before starting Neutron with the nsx plugin."
msgstr ""

#: neutron/plugins/vmware/common/config.py:140
msgid ""
"Unique identifier of the NSX L3 Gateway service which will be used for "
"implementing routers and floating IPs"
msgstr ""

#: neutron/plugins/vmware/common/config.py:144
msgid ""
"Unique identifier of the NSX L2 Gateway service which will be used by "
"default for network gateways"
msgstr ""

#: neutron/plugins/vmware/common/config.py:147
msgid ""
"Unique identifier of the Service Cluster which will be used by logical "
"services like dhcp and metadata"
msgstr ""

#: neutron/plugins/vmware/common/config.py:150
msgid ""
"Name of the interface on a L2 Gateway transport nodewhich should be used "
"by default when setting up a network connection"
msgstr ""

#: neutron/plugins/vmware/common/config.py:160
msgid "User name for vsm"
msgstr ""

#: neutron/plugins/vmware/common/config.py:164
msgid "Password for vsm"
msgstr ""

#: neutron/plugins/vmware/common/config.py:166
msgid "uri for vsm"
msgstr ""

#: neutron/plugins/vmware/common/config.py:168
msgid "Optional parameter identifying the ID of datacenter to deploy NSX Edges"
msgstr ""

#: neutron/plugins/vmware/common/config.py:171
#: neutron/plugins/vmware/common/config.py:177
msgid "Optional parameter identifying the ID of datastore to deploy NSX Edges"
msgstr ""

#: neutron/plugins/vmware/common/config.py:174
msgid "Optional parameter identifying the ID of resource to deploy NSX Edges"
msgstr ""

#: neutron/plugins/vmware/common/config.py:180
msgid "Network ID for physical network connectivity"
msgstr ""

#: neutron/plugins/vmware/common/config.py:183
msgid "Task status check interval"
msgstr ""

#: neutron/plugins/vmware/common/config.py:197
#, python-format
msgid "Invalid replication_mode: %s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:21
#, python-format
msgid "An unexpected error occurred in the NSX Plugin: %(err_msg)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:25
#, python-format
msgid "Unable to fulfill request with version %(version)s."
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:29
#, python-format
msgid "Invalid NSX connection parameters: %(conn_params)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:33
#, python-format
msgid ""
"Invalid cluster values: %(invalid_attrs)s. Please ensure that these "
"values are specified in the [DEFAULT] section of the NSX plugin ini file."
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:39
#, python-format
msgid "Unable to find cluster config entry for nova zone: %(nova_zone)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:44
#, python-format
msgid ""
"Unable to create port on network %(network)s. Maximum number of ports "
"reached"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:49
#, python-format
msgid ""
"While retrieving NAT rules, %(actual_rules)s were found whereas rules in "
"the (%(min_rules)s,%(max_rules)s) interval were expected"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:55
#, python-format
msgid "Invalid NSX attachment type '%(attachment_type)s'"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:59
msgid ""
"The networking backend is currently in maintenance mode and therefore "
"unable to accept requests which modify its state. Please try later."
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:65
#, python-format
msgid "Gateway Service %(gateway)s is already in use"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:69
msgid ""
"An invalid security certificate was specified for the gateway device. "
"Certificates must be enclosed between '-----BEGIN CERTIFICATE-----' and '"
"-----END CERTIFICATE-----'"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:76
#, python-format
msgid "Quota exceeded for Vcns resource: %(overs)s: %(err_msg)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:80
#, python-format
msgid "Router %(router_id)s is in use by Loadbalancer Service %(vip_id)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:85
#, python-format
msgid "Router %(router_id)s is in use by firewall Service %(firewall_id)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:90
#, python-format
msgid "Error happened in NSX VCNS Driver: %(err_msg)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:94
#, python-format
msgid ""
"Service cluster: '%(cluster_id)s' is unavailable. Please, check NSX setup"
" and/or configuration"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:99
#, python-format
msgid ""
"An error occurred while connecting LSN %(lsn_id)s and network %(net_id)s "
"via port %(port_id)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:108
#, python-format
msgid "Unable to find LSN for %(entity)s %(entity_id)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:112
#, python-format
msgid "Unable to find port for LSN %(lsn_id)s and %(entity)s %(entity_id)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:117
#, python-format
msgid "Unable to migrate network '%(net_id)s' to LSN: %(reason)s"
msgstr ""

#: neutron/plugins/vmware/common/exceptions.py:121
#, python-format
msgid "Configuration conflict on Logical Service Node %(lsn_id)s"
msgstr ""

#: neutron/plugins/vmware/common/sync.py:233
#, python-format
msgid ""
"Minimum request delay:%(req_delay)s must not exceed synchronization "
"interval:%(sync_interval)s"
msgstr ""

#: neutron/plugins/vmware/dbexts/lsn_db.py:86
#, python-format
msgid "Unable to find Logical Service Node for network %s"
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:46
#, python-format
msgid ""
"Network Gateway '%(gateway_id)s' still has active mappings with one or "
"more neutron networks."
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:51
#, python-format
msgid "Network Gateway %(gateway_id)s could not be found"
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:55
#, python-format
msgid ""
"Network Gateway Device '%(device_id)s' is still used by one or more "
"network gateways."
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:60
#, python-format
msgid "Network Gateway Device %(device_id)s could not be found."
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:64
#, python-format
msgid "One or more Network Gateway Devices could not be found: %(device_ids)s."
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:69
#, python-format
msgid ""
"Port '%(port_id)s' is owned by '%(device_owner)s' and therefore cannot be"
" deleted directly via the port API."
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:74
#, python-format
msgid ""
"The specified mapping '%(mapping)s' is already in use on network gateway "
"'%(gateway_id)s'."
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:79
#, python-format
msgid ""
"Multiple network connections found on '%(gateway_id)s' with provided "
"criteria."
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:84
#, python-format
msgid ""
"The connection %(network_mapping_info)s was not found on the network "
"gateway '%(network_gateway_id)s'"
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:89
#, python-format
msgid "The network gateway %(gateway_id)s cannot be updated or deleted"
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:197
msgid ""
"A network identifier must be specified when connecting a network to a "
"network gateway. Unable to complete operation"
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:203
#, python-format
msgid ""
"Invalid keys found among the ones provided in request body: "
"%(connection_attrs)s."
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:211
msgid "Cannot specify a segmentation id when the segmentation type is flat"
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:215
#, python-format
msgid "Invalid segmentation id (%d) for vlan segmentation type"
msgstr ""

#: neutron/plugins/vmware/dbexts/networkgw_db.py:369
#, python-format
msgid ""
"Requested network '%(network_id)s' not found.Unable to create network "
"connection on gateway '%(network_gateway_id)s"
msgstr ""

#: neutron/plugins/vmware/dbexts/vcns_db.py:77
#, python-format
msgid "Rule Resource binding with id:%s not found!"
msgstr ""

#: neutron/plugins/vmware/dbexts/vcns_db.py:94
msgid "Rule Resource binding not found!"
msgstr ""

#: neutron/plugins/vmware/dbexts/vcns_db.py:123
#: neutron/plugins/vmware/dbexts/vcns_db.py:133
#, python-format
msgid "VIP Resource binding with id:%s not found!"
msgstr ""

#: neutron/plugins/vmware/dbexts/vcns_db.py:162
#, python-format
msgid ""
"Pool Resource binding with edge_id:%(edge_id)s pool_vseid:%(pool_vseid)s "
"not found!"
msgstr ""

#: neutron/plugins/vmware/dbexts/vcns_db.py:174
#, python-format
msgid "Pool Resource binding with id:%s not found!"
msgstr ""

#: neutron/plugins/vmware/dbexts/vcns_db.py:200
#, python-format
msgid "Monitor Resource binding with id:%s not found!"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:41
msgid ""
"Pull LSN information from NSX in case it is missing from the local data "
"store. This is useful to rebuild the local store in case of server "
"recovery."
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:87
#, python-format
msgid "Unable to create LSN for network %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:164
#, python-format
msgid "Unable to create port for LSN  %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:277
#, python-format
msgid ""
"Unable to configure dhcp for Logical Service Node %(lsn_id)s and port "
"%(lsn_port_id)s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:298
#, python-format
msgid "Unable to configure metadata for subnet %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:392
#, python-format
msgid "Unable to save LSN for network %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/lsnmanager.py:458
#, python-format
msgid "Unable to save LSN port for subnet %s"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/migration.py:113
msgid "LSN already exist"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/migration.py:117
msgid "Cannot migrate an external network"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/migration.py:126
msgid "Cannot migrate a 'metadata' network"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/migration.py:129
msgid "Unable to support multiple subnets per network"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/nsx.py:40
msgid "Comma separated list of additional domain name servers"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/nsx.py:48
msgid "Default DHCP lease time"
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/nsx.py:56
msgid "IP address used by Metadata server."
msgstr ""

#: neutron/plugins/vmware/dhcp_meta/nsx.py:60
msgid "TCP Port used by Metadata server."
msgstr ""

#: neutron/plugins/vmware/extensions/networkgw.py:84
msgid "Cannot create a gateway with an empty device list"
msgstr ""

#: neutron/plugins/vmware/extensions/networkgw.py:100
#, python-format
msgid "Unexpected keys found in device description:%s"
msgstr ""

#: neutron/plugins/vmware/extensions/networkgw.py:104
#, python-format
msgid "%s: provided data are not iterable"
msgstr ""

#: neutron/plugins/vmware/extensions/networkgw.py:111
msgid "A connector type is required to create a gateway device"
msgstr ""

#: neutron/plugins/vmware/extensions/networkgw.py:120
#, python-format
msgid "Unknown connector type: %s"
msgstr ""

#: neutron/plugins/vmware/extensions/networkgw.py:127
msgid "Number of network gateways allowed per tenant, -1 for unlimited"
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:34
msgid "Need to be admin in order to create queue called default"
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:38
msgid "Default queue already exists."
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:42
#, python-format
msgid "Invalid value for dscp %(data)s must be integer value between 0 and 63."
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:47
msgid "The qos marking cannot be set to 'trusted' when the DSCP field is set"
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:52
msgid "Invalid bandwidth rate, min greater than max."
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:56
#, python-format
msgid "Invalid bandwidth rate, %(data)s must be a non negative integer."
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:61
#, python-format
msgid "Queue %(id)s does not exist"
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:65
msgid "Unable to delete queue attached to port."
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:69
msgid "Port is not associated with lqueue"
msgstr ""

#: neutron/plugins/vmware/extensions/qos.py:80
#, python-format
msgid "'%s' must be a non negative integer."
msgstr ""

#: neutron/plugins/vmware/nsxlib/__init__.py:83
#, python-format
msgid "Error. %(type)s exception: %(exc)s."
msgstr ""

#: neutron/plugins/vmware/nsxlib/__init__.py:87
#, python-format
msgid "locals=[%s]"
msgstr ""

#: neutron/plugins/vmware/nsxlib/lsn.py:172
#, python-format
msgid ""
"Attempt to plug Logical Services Node %(lsn)s into network with port "
"%(port)s failed. PatchAttachment already exists with another port"
msgstr ""

#: neutron/plugins/vmware/nsxlib/router.py:454
#, python-format
msgid "Invalid keys for NAT match: %s"
msgstr ""

#: neutron/plugins/vmware/nsxlib/router.py:627
#, python-format
msgid "Router Port %(lport_id)s not found on router %(lrouter_id)s"
msgstr ""

#: neutron/plugins/vmware/nsxlib/router.py:632
#, python-format
msgid ""
"An exception occurred while updating IP addresses on a router logical "
"port:%s"
msgstr ""

#: neutron/plugins/vmware/nsxlib/switch.py:257
msgid "Unable to get ports"
msgstr ""

#: neutron/plugins/vmware/nsxlib/versioning.py:56
msgid "Operation may not be supported"
msgstr ""

#: neutron/plugins/vmware/nsxlib/versioning.py:64
msgid ""
"NSX version is not set. Unable to complete request correctly. Check log "
"for NSX communication errors."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:254
#, python-format
msgid ""
"Unable to create logical router port for neutron port id %(port_id)s on "
"router %(nsx_router_id)s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:345
#, python-format
msgid ""
"Unable to plug attachment in router port %(r_port_id)s for neutron port "
"id %(q_port_id)s on router %(router_id)s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:391
msgid "An exception occurred while selecting logical switch for the port"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:550
#, python-format
msgid ""
"It is not allowed to create router interface ports on external networks "
"as '%s'"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:588
#, python-format
msgid ""
"device_id field must be populated in order to create an external gateway "
"port for network %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:598
#, python-format
msgid "The gateway port for the NSX router %s was not found on the backend"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:674
#, python-format
msgid "Logical router resource %s not found on NSX platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:678
#: neutron/plugins/vmware/plugins/base.py:1764
msgid "Unable to update logical routeron NSX Platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:771
#, python-format
msgid "%s required"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:776
msgid "Segmentation ID cannot be specified with flat network type"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:780
msgid "Segmentation ID must be specified with vlan network type"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:784
#: neutron/plugins/vmware/plugins/base.py:803
#, python-format
msgid "%(segmentation_id)s out of range (%(min_id)s through %(max_id)s)"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:809
#, python-format
msgid "%(net_type_param)s %(net_type_value)s not supported"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1054
msgid "admin_state_up=False networks are not supported."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1378
msgid ""
"Cannot create a distributed router with the NSX platform currently in "
"execution. Please, try without specifying the 'distributed' attribute."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1384
msgid "Unable to create logical router on NSX Platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1406
#, python-format
msgid "Unable to create router %s on NSX backend"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1435
#: neutron/plugins/vmware/plugins/base.py:1520
#: neutron/plugins/vmware/plugins/service.py:211
#: neutron/plugins/vmware/plugins/service.py:1249
#, python-format
msgid "Network '%s' is not a valid external network"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1529
msgid ""
"'routes' cannot contain route '0.0.0.0/0', this must be updated through "
"the default gateway attribute"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1545
#, python-format
msgid "Logical router %s not found on NSX Platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1549
msgid "Unable to update logical router on NSX Platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1551
msgid ""
"Request cannot contain 'routes' with the NSX platform currently in "
"execution. Please, try without specifying the static routes."
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1612
#, python-format
msgid "Unable to delete logical router '%s' on NSX Platform"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:1949
msgid "Failed to update NAT rules for floatingip update"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2032
#, python-format
msgid "Unable to create l2_gw_service for: %s"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2394
#, python-format
msgid "Unable to remove security group %s from backend"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2407
#, python-format
msgid "Port values not valid for protocol: %s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:434
#, python-format
msgid "An exception occurred while creating a port on lswitch %s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:449
#, python-format
msgid "Unable to create port on NSX logical router %s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:482
#, python-format
msgid "Unable to create integration logic switch for router %s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:492
#, python-format
msgid "Unable to add router interface to integration lswitch for router %s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:502
#, python-format
msgid "Unable to create advance service router for %s"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:919
#: neutron/plugins/vmware/plugins/service.py:1235
msgid "router_id is not provided!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:923
#: neutron/plugins/vmware/plugins/service.py:1623
#, python-format
msgid "router_id:%s is not an advanced router!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:928
msgid "A firewall is already associated with the router"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1162
#, python-format
msgid ""
"Operation can't be performed, Since resource %(model)s : %(id)s is in "
"DELETEing status!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1171
#, python-format
msgid "Resource %(model)s : %(id)s not found!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1240
#, python-format
msgid "router_id: %s is not an advanced router!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1508
msgid "Vcns right now can only support one monitor per pool"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1585
#, python-format
msgid ""
"Failed to update ipsec vpn configuration on edge, since the router: %s "
"does not have a gateway yet!"
msgstr ""

#: neutron/plugins/vmware/plugins/service.py:1628
#, python-format
msgid "a vpnservice is already associated with the router: %s"
msgstr ""

#: neutron/plugins/vmware/shell/commands.py:24
#, python-format
msgid ""
"\n"
"Service type = %s\n"
msgstr ""

#: neutron/plugins/vmware/shell/commands.py:27
#, python-format
msgid "Service uuids = %s\n"
msgstr ""

#: neutron/plugins/vmware/shell/commands.py:28
#, python-format
msgid ""
"Port uuids = %s\n"
"\n"
msgstr ""

#: neutron/plugins/vmware/shell/commands.py:37
msgid "ID or name of network to run report on"
msgstr ""

#: neutron/plugins/vmware/shell/commands.py:46
msgid "Migration report is:\n"
msgstr ""

#: neutron/plugins/vmware/shell/commands.py:56
msgid "ID or name of network to migrate"
msgstr ""

#: neutron/plugins/vmware/shell/commands.py:66
msgid "Migration has been successful:\n"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_appliance_driver.py:187
#, python-format
msgid "Vnic %d currently not supported"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:41
#, python-format
msgid "Invalid action value %s in a firewall rule"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:50
#, python-format
msgid "Invalid action value %s in a vshield firewall rule"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:208
#, python-format
msgid "No rule id:%s found in the edge_firewall_binding"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_firewall_driver.py:350
msgid "Can't execute insert rule operation without reference rule_id"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:52
#, python-format
msgid ""
"Unsupported ike_version: %s! Only 'v1' ike version is supported on "
"vshield Edge!"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:74
#, python-format
msgid ""
"Unsupported encryption_algorithm: %s! '3des', 'aes-128' and 'aes-256' are"
" supported on VSE right now."
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:83
#, python-format
msgid "Unsupported pfs: %s! 'group2' and 'group5' are supported on VSE right now."
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:91
#, python-format
msgid ""
"Unsupported transform protocol: %s! 'esp' is supported by default on VSE "
"right now."
msgstr ""

#: neutron/plugins/vmware/vshield/edge_ipsecvpn_driver.py:100
#, python-format
msgid ""
"Unsupported encapsulation mode: %s! 'tunnel' is supported by default on "
"VSE right now."
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:157
#, python-format
msgid "Invalid %(protocol)s persistence method: %(type)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:212
#, python-format
msgid "vip_binding not found with id: %(id)s edge_id: %(edge_id)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:304
#, python-format
msgid "pool_binding not found with id: %(id)s edge_id: %(edge_id)s"
msgstr ""

#: neutron/plugins/vmware/vshield/edge_loadbalancer_driver.py:364
#, python-format
msgid "monitor_binding not found with id: %(id)s edge_id: %(edge_id)s"
msgstr ""

#: neutron/plugins/vmware/vshield/common/exceptions.py:33
#, python-format
msgid "%(resource)s not found: %(msg)s"
msgstr ""

#: neutron/plugins/vmware/vshield/common/exceptions.py:37
#, python-format
msgid "An unknown exception %(status)s occurred: %(response)s."
msgstr ""

#: neutron/plugins/vmware/vshield/common/exceptions.py:48
#, python-format
msgid "Resource %(uri)s has been redirected"
msgstr ""

#: neutron/plugins/vmware/vshield/common/exceptions.py:52
#, python-format
msgid "Request %(uri)s is Bad, response %(response)s"
msgstr ""

#: neutron/plugins/vmware/vshield/common/exceptions.py:56
#, python-format
msgid "Forbidden: %(uri)s"
msgstr ""

#: neutron/plugins/vmware/vshield/common/exceptions.py:60
#, python-format
msgid "Resource %(uri)s not found"
msgstr ""

#: neutron/plugins/vmware/vshield/common/exceptions.py:64
#, python-format
msgid "Media Type %(uri)s is not supported"
msgstr ""

#: neutron/plugins/vmware/vshield/common/exceptions.py:68
#, python-format
msgid "Service Unavailable: %(uri)s"
msgstr ""

#: neutron/plugins/vmware/vshield/tasks/tasks.py:47
#, python-format
msgid "Invalid state %(state)d"
msgstr ""

#: neutron/plugins/vmware/vshield/tasks/tasks.py:51
#, python-format
msgid "State %(state)d skipped. Current state %(current)d"
msgstr ""

#: neutron/server/__init__.py:40
msgid ""
"ERROR: Unable to find configuration file via the default search paths "
"(~/.neutron/, ~/, /etc/neutron/, /etc/) and the '--config-file' option!"
msgstr ""

#: neutron/server/__init__.py:65
#, python-format
msgid "ERROR: %s"
msgstr ""

#: neutron/services/provider_configuration.py:27
msgid ""
"Defines providers for advanced services using the format: "
"<service_type>:<name>:<driver>[:default]"
msgstr ""

#: neutron/services/provider_configuration.py:45
#, python-format
msgid "Provider name is limited by 255 characters: %s"
msgstr ""

#: neutron/services/provider_configuration.py:54
msgid "Invalid service provider format"
msgstr ""

#: neutron/services/provider_configuration.py:62
#, python-format
msgid "Invalid provider format. Last part should be 'default' or empty: %s"
msgstr ""

#: neutron/services/provider_configuration.py:68
#, python-format
msgid "Service type '%(svc_type)s' is not allowed, allowed types: %(allowed)s"
msgstr ""

#: neutron/services/provider_configuration.py:82
#, python-format
msgid ""
"Service provider '%(provider)s' could not be found for service type "
"%(service_type)s"
msgstr ""

#: neutron/services/provider_configuration.py:87
#, python-format
msgid "Service type %(service_type)s does not have a default service provider"
msgstr ""

#: neutron/services/provider_configuration.py:92
#, python-format
msgid ""
"Resource '%(resource_id)s' is already associated with provider "
"'%(provider)s' for service type '%(service_type)s'"
msgstr ""

#: neutron/services/provider_configuration.py:105
#, python-format
msgid "Driver %s is not unique across providers"
msgstr ""

#: neutron/services/provider_configuration.py:115
#, python-format
msgid "Multiple default providers for service %s"
msgstr ""

#: neutron/services/provider_configuration.py:126
#, python-format
msgid "Multiple providers specified for service %s"
msgstr ""

#: neutron/services/service_base.py:71
#, python-format
msgid "No providers specified for '%s' service, exiting"
msgstr ""

#: neutron/services/firewall/agents/firewall_agent_api.py:28
msgid "Name of the FWaaS Driver"
msgstr ""

#: neutron/services/firewall/agents/firewall_agent_api.py:32
msgid "Enable FWaaS"
msgstr ""

#: neutron/services/firewall/agents/l3reference/firewall_l3_agent.py:67
msgid ""
"FWaaS plugin is configured in the server side, but FWaaS is disabled in "
"L3-agent."
msgstr ""

#: neutron/services/firewall/agents/l3reference/firewall_l3_agent.py:79
#, python-format
msgid "Error importing FWaaS device driver: %s"
msgstr ""

#: neutron/services/l3_router/l3_apic.py:57
msgid "L3 Router Service Plugin for basic L3 using the APIC"
msgstr ""

#: neutron/services/l3_router/brocade/l3_router_plugin.py:43
msgid "Rbridge id of provider edge router(s)"
msgstr ""

#: neutron/services/l3_router/brocade/l3_router_plugin.py:162
msgid "BrocadeSVIPlugin: adding redundant router interface is not supported"
msgstr ""

#: neutron/services/metering/agents/metering_agent.py:71
msgid "Metering driver"
msgstr ""

#: neutron/services/metering/agents/metering_agent.py:73
msgid "Interval between two metering measures"
msgstr ""

#: neutron/services/metering/agents/metering_agent.py:75
msgid "Interval between two metering reports"
msgstr ""

#: neutron/services/metering/agents/metering_agent.py:101
msgid "A metering driver must be specified"
msgstr ""

#: neutron/services/metering/drivers/iptables/iptables_driver.py:91
msgid "An interface driver must be specified"
msgstr ""

#: neutron/tests/functional/agent/linux/simple_daemon.py:37
msgid ""
"uuid provided from the command line so external_process can track us via "
"/proc/cmdline interface."
msgstr ""

#: neutron/tests/unit/test_api_v2_resource.py:157
#: neutron/tests/unit/test_api_v2_resource.py:202
msgid "Unmapped error"
msgstr ""

#: neutron/tests/unit/test_api_v2_resource.py:268
msgid ""
"The server has either erred or is incapable of performing the requested "
"operation."
msgstr ""

#: neutron/tests/unit/test_iptables_manager.py:858
#: neutron/tests/unit/test_iptables_manager.py:892
#, python-format
msgid ""
"IPTablesManager.apply failed to apply the following set of iptables "
"rules:\n"
"%s"
msgstr ""

#: neutron/tests/unit/bigswitch/fake_server.py:122
#, python-format
msgid "No floating IPs in requesturi=%(uri)s, body=%(body)s"
msgstr ""

#: neutron/tests/unit/bigswitch/fake_server.py:131
#, python-format
msgid "Expected floating IPs from multiple tenants.uri=%(uri)s, body=%(body)s"
msgstr ""

#: neutron/tests/unit/bigswitch/fake_server.py:176
#, python-format
msgid "No host cert for %(server)s in cert %(cert)s"
msgstr ""

#: neutron/tests/unit/ml2/test_ml2_plugin.py:149
#, python-format
msgid "Deleting port %s"
msgstr ""

#: neutron/tests/unit/ml2/test_ml2_plugin.py:150
#, python-format
msgid "The port '%s' was deleted"
msgstr ""

#: neutron/tests/unit/ml2/drivers/mechanism_logger.py:32
#, python-format
msgid ""
"%(method)s called with network settings %(current)s (original settings "
"%(original)s) and network segments %(segments)s"
msgstr ""

#: neutron/tests/unit/ml2/drivers/mechanism_logger.py:59
#, python-format
msgid ""
"%(method)s called with subnet settings %(current)s (original settings "
"%(original)s)"
msgstr ""

#: neutron/tests/unit/ml2/drivers/mechanism_logger.py:85
#, python-format
msgid ""
"%(method)s called with port settings %(current)s (original settings "
"%(original)s) bound to segment %(segment)s (original segment "
"%(original_segment)s) using driver %(driver)s (original driver "
"%(original_driver)s) on network %(network)s"
msgstr ""

#: neutron/tests/unit/ml2/drivers/brocade/test_brocade_l3_plugin.py:44
#, python-format
msgid "rbridge id %s"
msgstr ""

#: neutron/tests/unit/ml2/extensions/test_extension.py:54
msgid "Adds test attributes to core resources."
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:64
#, python-format
msgid "(create_tenant) OFC tenant %s already exists"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:76
#, python-format
msgid "(delete_tenant) OFC tenant %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:85
#, python-format
msgid "(create_network) OFC tenant %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:88
#, python-format
msgid "(create_network) OFC network %s already exists"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:99
#, python-format
msgid "(update_network) OFC network %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:111
#, python-format
msgid "(delete_network) OFC network %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:120
#, python-format
msgid "(create_port) OFC network %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:123
#, python-format
msgid "(create_port) OFC port %s already exists"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:137
#, python-format
msgid "(delete_port) OFC port %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:171
#, python-format
msgid "(create_router) OFC tenant %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:174
#, python-format
msgid "(create_router) OFC router %s already exists"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:177
msgid "Operation on OFC is failed"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:191
#: neutron/tests/unit/nec/stub_ofc_driver.py:281
#, python-format
msgid "(delete_router) OFC router %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:201
#, python-format
msgid "(add_router_interface) ip_address %s is not a valid format (a.b.c.d/N)."
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:206
#, python-format
msgid "(add_router_interface) OFC router %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:209
#, python-format
msgid "(add_router_interface) OFC network %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:224
#: neutron/tests/unit/nec/stub_ofc_driver.py:241
#, python-format
msgid "(delete_router_interface) OFC router interface %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:254
#, python-format
msgid "(add_router_route) OFC router %s not found"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:259
#, python-format
msgid "(add_router_route) route to \"%s\" already exists"
msgstr ""

#: neutron/tests/unit/nec/stub_ofc_driver.py:273
#, python-format
msgid "(delete_router_route) OFC router route %s not found"
msgstr ""

#: neutron/tests/unit/nec/test_ofc_client.py:84
msgid "The specified OFC resource (/somewhere) is not found."
msgstr ""

#: neutron/tests/unit/nec/test_ofc_client.py:88
#: neutron/tests/unit/nec/test_ofc_client.py:94
#: neutron/tests/unit/nec/test_ofc_client.py:103
msgid "An OFC exception has occurred: Operation on OFC failed"
msgstr ""

#: neutron/tests/unit/nec/test_ofc_client.py:110
msgid "An OFC exception has occurred: Failed to connect OFC : "
msgstr ""

#: neutron/tests/unit/ofagent/test_ofa_neutron_agent.py:754
#: neutron/tests/unit/ofagent/test_ofa_neutron_agent.py:774
#: neutron/tests/unit/openvswitch/test_ovs_neutron_agent.py:1337
#: neutron/tests/unit/openvswitch/test_ovs_neutron_agent.py:1357
#: neutron/tests/unit/openvswitch/test_ovs_neutron_agent.py:1374
#, python-format
msgid "Failed to set-up %(type)s tunnel port to %(ip)s"
msgstr ""

#: neutron/tests/unit/ofagent/test_ofa_neutron_agent.py:771
#: neutron/tests/unit/openvswitch/test_ovs_neutron_agent.py:1354
msgid "ofport should have a value that can be interpreted as an integer"
msgstr ""

#: neutron/tests/unit/vmware/apiclient/fake.py:406
#, python-format
msgid "lswitch:%s not found"
msgstr ""

#: neutron/tests/unit/vmware/apiclient/fake.py:415
#, python-format
msgid "lrouter:%s not found"
msgstr ""

#: neutron/tests/unit/vmware/vshield/fake_vcns.py:105
#, python-format
msgid "Job %s does not nexist"
msgstr ""

#: neutron/tests/unit/vmware/vshield/fake_vcns.py:117
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:128
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:145
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:163
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:185
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:207
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:292
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:306
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:320
#: neutron/tests/unit/vmware/vshield/fake_vcns.py:362
#, python-format
msgid "Edge %s does not exist"
msgstr ""

#: neutron/tests/unit/vmware/vshield/fake_vcns.py:195
#, python-format
msgid "Rule id %d doest not exist"
msgstr ""

#: neutron/tests/unit/vmware/vshield/fake_vcns.py:259
#, python-format
msgid "Lswitch %s does not exist"
msgstr ""

#: neutron/tests/unit/vmware/vshield/test_edge_router.py:129
msgid "Tasks not completed"
msgstr ""

